
import FreeCAD
import FreeCADGui
from FreeCAD import Base
import QW_Modeller
from qw_project import *
import Part
import Sketcher
from qw_units import *
from qw_paths import *

setGHzBaseFreqUnit()
setmmBaseGeomUnit()

def set_GeometryAndMedia(qwm_doc):
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_subref')
    qwm_doc.sketch_subref.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.0,0.0,0), FreeCAD.Vector(434.0,0.0,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.0,0.0,0), FreeCAD.Vector(434.00280987233975,0.46716928069502894,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.00280987233975,0.46716928069502894,0), FreeCAD.Vector(434.00632218706363,0.7007539210425434,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.00632218706363,0.7007539210425434,0), FreeCAD.Vector(434.01123937970357,0.9343385613900579,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.01123937970357,0.9343385613900579,0), FreeCAD.Vector(434.0175614022889,1.1679232017375725,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.0175614022889,1.1679232017375725,0), FreeCAD.Vector(434.0252881931472,1.401507842085087,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.0252881931472,1.401507842085087,0), FreeCAD.Vector(434.03441967690696,1.6350924824326016,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.03441967690696,1.6350924824326016,0), FreeCAD.Vector(434.04495576450154,1.8686771227801162,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.04495576450154,1.8686771227801162,0), FreeCAD.Vector(434.05689635317344,2.102261763127631,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.05689635317344,2.102261763127631,0), FreeCAD.Vector(434.0702413264792,2.3358464034751454,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.0702413264792,2.3358464034751454,0), FreeCAD.Vector(434.0849905542955,2.56943104382266,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.0849905542955,2.56943104382266,0), FreeCAD.Vector(434.1011438928248,2.8030156841701745,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.1011438928248,2.8030156841701745,0), FreeCAD.Vector(434.11870118460297,3.036600324517689,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.11870118460297,3.036600324517689,0), FreeCAD.Vector(434.13766225850657,3.2701849648652037,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.13766225850657,3.2701849648652037,0), FreeCAD.Vector(434.15802692976155,3.5037696052127183,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.15802692976155,3.5037696052127183,0), FreeCAD.Vector(434.1797949999517,3.737354245560233,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.1797949999517,3.737354245560233,0), FreeCAD.Vector(434.202966257029,3.9709388859077475,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.202966257029,3.9709388859077475,0), FreeCAD.Vector(434.2275404753233,4.204523526255262,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.2275404753233,4.204523526255262,0), FreeCAD.Vector(434.2535174155537,4.438108166602776,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.2535174155537,4.438108166602776,0), FreeCAD.Vector(434.28089682483994,4.67169280695029,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.28089682483994,4.67169280695029,0), FreeCAD.Vector(434.3096784367151,4.905277447297804,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.3096784367151,4.905277447297804,0), FreeCAD.Vector(434.33986197113774,5.138862087645318,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.33986197113774,5.138862087645318,0), FreeCAD.Vector(434.3714471345065,5.372446727992832,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.3714471345065,5.372446727992832,0), FreeCAD.Vector(434.4044336196735,5.606031368340346,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.4044336196735,5.606031368340346,0), FreeCAD.Vector(434.4388211059599,5.839616008687861,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.4388211059599,5.839616008687861,0), FreeCAD.Vector(434.474609259171,6.073200649035375,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.474609259171,6.073200649035375,0), FreeCAD.Vector(434.51179773161255,6.306785289382889,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.51179773161255,6.306785289382889,0), FreeCAD.Vector(434.5503861621076,6.540369929730403,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.5503861621076,6.540369929730403,0), FreeCAD.Vector(434.5903741760142,6.773954570077917,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.5903741760142,6.773954570077917,0), FreeCAD.Vector(434.6317613852431,7.007539210425431,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.6317613852431,7.007539210425431,0), FreeCAD.Vector(434.67454738827695,7.241123850772945,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.67454738827695,7.241123850772945,0), FreeCAD.Vector(434.7187317701895,7.4747084911204595,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.7187317701895,7.4747084911204595,0), FreeCAD.Vector(434.7643141026654,7.708293131467974,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.7643141026654,7.708293131467974,0), FreeCAD.Vector(434.81129394402154,7.941877771815488,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.81129394402154,7.941877771815488,0), FreeCAD.Vector(434.85967083922753,8.175462412163002,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.85967083922753,8.175462412163002,0), FreeCAD.Vector(434.9094443199281,8.409047052510516,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.9094443199281,8.409047052510516,0), FreeCAD.Vector(434.960613904466,8.64263169285803,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.960613904466,8.64263169285803,0), FreeCAD.Vector(435.01317909790407,8.876216333205544,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.01317909790407,8.876216333205544,0), FreeCAD.Vector(435.06713939205025,9.109800973553059,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.06713939205025,9.109800973553059,0), FreeCAD.Vector(435.12249426548124,9.343385613900573,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.12249426548124,9.343385613900573,0), FreeCAD.Vector(435.17924318356796,9.576970254248087,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.17924318356796,9.576970254248087,0), FreeCAD.Vector(435.23738559850057,9.810554894595601,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.23738559850057,9.810554894595601,0), FreeCAD.Vector(435.2969209493158,10.044139534943115,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.2969209493158,10.044139534943115,0), FreeCAD.Vector(435.3578486619225,10.27772417529063,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.3578486619225,10.27772417529063,0), FreeCAD.Vector(435.4201681491303,10.511308815638143,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.4201681491303,10.511308815638143,0), FreeCAD.Vector(435.4838788106765,10.744893455985657,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.4838788106765,10.744893455985657,0), FreeCAD.Vector(435.5489800332562,10.978478096333172,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.5489800332562,10.978478096333172,0), FreeCAD.Vector(435.61547119054995,11.212062736680686,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.61547119054995,11.212062736680686,0), FreeCAD.Vector(435.68335164325487,11.4456473770282,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.68335164325487,11.4456473770282,0), FreeCAD.Vector(435.75262073911404,11.679232017375714,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.75262073911404,11.679232017375714,0), FreeCAD.Vector(435.82327781294885,11.912816657723228,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.82327781294885,11.912816657723228,0), FreeCAD.Vector(435.895322186689,12.146401298070742,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.895322186689,12.146401298070742,0), FreeCAD.Vector(435.9687531694059,12.379985938418256,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.9687531694059,12.379985938418256,0), FreeCAD.Vector(436.04357005734494,12.61357057876577,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.04357005734494,12.61357057876577,0), FreeCAD.Vector(436.1197721339587,12.847155219113285,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.1197721339587,12.847155219113285,0), FreeCAD.Vector(436.1973586699413,13.080739859460799,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.1973586699413,13.080739859460799,0), FreeCAD.Vector(436.27632892326227,13.314324499808313,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.27632892326227,13.314324499808313,0), FreeCAD.Vector(436.35668213920195,13.547909140155827,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.35668213920195,13.547909140155827,0), FreeCAD.Vector(436.4384175503871,13.781493780503341,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.4384175503871,13.781493780503341,0), FreeCAD.Vector(436.52153437682654,14.015078420850855,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.52153437682654,14.015078420850855,0), FreeCAD.Vector(436.6060318259483,14.24866306119837,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.6060318259483,14.24866306119837,0), FreeCAD.Vector(436.691909092637,14.482247701545884,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.691909092637,14.482247701545884,0), FreeCAD.Vector(436.7791653592704,14.715832341893398,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.7791653592704,14.715832341893398,0), FreeCAD.Vector(436.8677997957594,14.949416982240912,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.8677997957594,14.949416982240912,0), FreeCAD.Vector(436.95781155958576,15.183001622588426,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.95781155958576,15.183001622588426,0), FreeCAD.Vector(437.04919979584133,15.41658626293594,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.04919979584133,15.41658626293594,0), FreeCAD.Vector(437.1419636372688,15.650170903283454,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.1419636372688,15.650170903283454,0), FreeCAD.Vector(437.2361022043011,15.883755543630969,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.2361022043011,15.883755543630969,0), FreeCAD.Vector(437.331614605103,16.117340183978484,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.331614605103,16.117340183978484,0), FreeCAD.Vector(437.4284999356123,16.350924824326,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.4284999356123,16.350924824326,0), FreeCAD.Vector(437.5267572795816,16.584509464673516,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.5267572795816,16.584509464673516,0), FreeCAD.Vector(437.6263857086208,16.818094105021032,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.6263857086208,16.818094105021032,0), FreeCAD.Vector(437.72738428224005,17.051678745368548,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.72738428224005,17.051678745368548,0), FreeCAD.Vector(437.8297520478933,17.285263385716064,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.8297520478933,17.285263385716064,0), FreeCAD.Vector(437.93348804102214,17.51884802606358,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.93348804102214,17.51884802606358,0), FreeCAD.Vector(438.03859128509964,17.752432666411096,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.03859128509964,17.752432666411096,0), FreeCAD.Vector(438.1450607916761,17.98601730675861,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.1450607916761,17.98601730675861,0), FreeCAD.Vector(438.25289556042367,18.219601947106128,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.25289556042367,18.219601947106128,0), FreeCAD.Vector(438.3620945791825,18.453186587453644,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.3620945791825,18.453186587453644,0), FreeCAD.Vector(438.472656824007,18.68677122780116,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.472656824007,18.68677122780116,0), FreeCAD.Vector(438.5845812592123,18.920355868148675,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.5845812592123,18.920355868148675,0), FreeCAD.Vector(438.6978668374219,19.15394050849619,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.6978668374219,19.15394050849619,0), FreeCAD.Vector(438.81251249961457,19.387525148843707,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.81251249961457,19.387525148843707,0), FreeCAD.Vector(438.9285171751732,19.621109789191223,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.9285171751732,19.621109789191223,0), FreeCAD.Vector(439.04587978193297,19.85469442953874,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(439.04587978193297,19.85469442953874,0), FreeCAD.Vector(439.16459922623017,20.088279069886255,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(439.16459922623017,20.088279069886255,0), FreeCAD.Vector(439.28467440295174,20.32186371023377,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(439.28467440295174,20.32186371023377,0), FreeCAD.Vector(439.40610419558504,20.555448350581287,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(439.40610419558504,20.555448350581287,0), FreeCAD.Vector(439.5288874762681,20.789032990928803,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(439.5288874762681,20.789032990928803,0), FreeCAD.Vector(439.65302310584036,21.02261763127632,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(439.65302310584036,21.02261763127632,0), FreeCAD.Vector(439.7785099338935,21.256202271623835,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(439.7785099338935,21.256202271623835,0), FreeCAD.Vector(439.90534679882285,21.48978691197135,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(439.90534679882285,21.48978691197135,0), FreeCAD.Vector(440.03353252787963,21.723371552318866,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(440.03353252787963,21.723371552318866,0), FreeCAD.Vector(440.1630659372229,21.956956192666382,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(440.1630659372229,21.956956192666382,0), FreeCAD.Vector(440.2939458319721,22.1905408330139,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(440.2939458319721,22.1905408330139,0), FreeCAD.Vector(440.42617100626035,22.424125473361414,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(440.42617100626035,22.424125473361414,0), FreeCAD.Vector(440.5597402432879,22.65771011370893,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(440.5597402432879,22.65771011370893,0), FreeCAD.Vector(440.6946523153753,22.891294754056446,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(440.6946523153753,22.891294754056446,0), FreeCAD.Vector(440.83090598401833,23.124879394403962,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(440.83090598401833,23.124879394403962,0), FreeCAD.Vector(440.96849999994197,23.358464034751478,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(440.96849999994197,23.358464034751478,0), FreeCAD.Vector(438.96849999994197,23.358464034751478,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.96849999994197,23.358464034751478,0), FreeCAD.Vector(438.83090598401833,23.124879394403962,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.83090598401833,23.124879394403962,0), FreeCAD.Vector(438.6946523153753,22.891294754056446,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.6946523153753,22.891294754056446,0), FreeCAD.Vector(438.5597402432879,22.65771011370893,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.5597402432879,22.65771011370893,0), FreeCAD.Vector(438.42617100626035,22.424125473361414,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.42617100626035,22.424125473361414,0), FreeCAD.Vector(438.2939458319721,22.1905408330139,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.2939458319721,22.1905408330139,0), FreeCAD.Vector(438.1630659372229,21.956956192666382,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.1630659372229,21.956956192666382,0), FreeCAD.Vector(438.03353252787963,21.723371552318866,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(438.03353252787963,21.723371552318866,0), FreeCAD.Vector(437.90534679882285,21.48978691197135,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.90534679882285,21.48978691197135,0), FreeCAD.Vector(437.7785099338935,21.256202271623835,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.7785099338935,21.256202271623835,0), FreeCAD.Vector(437.65302310584036,21.02261763127632,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.65302310584036,21.02261763127632,0), FreeCAD.Vector(437.5288874762681,20.789032990928803,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.5288874762681,20.789032990928803,0), FreeCAD.Vector(437.40610419558504,20.555448350581287,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.40610419558504,20.555448350581287,0), FreeCAD.Vector(437.28467440295174,20.32186371023377,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.28467440295174,20.32186371023377,0), FreeCAD.Vector(437.16459922623017,20.088279069886255,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.16459922623017,20.088279069886255,0), FreeCAD.Vector(437.04587978193297,19.85469442953874,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(437.04587978193297,19.85469442953874,0), FreeCAD.Vector(436.9285171751732,19.621109789191223,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.9285171751732,19.621109789191223,0), FreeCAD.Vector(436.81251249961457,19.387525148843707,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.81251249961457,19.387525148843707,0), FreeCAD.Vector(436.6978668374219,19.15394050849619,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.6978668374219,19.15394050849619,0), FreeCAD.Vector(436.5845812592123,18.920355868148675,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.5845812592123,18.920355868148675,0), FreeCAD.Vector(436.472656824007,18.68677122780116,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.472656824007,18.68677122780116,0), FreeCAD.Vector(436.3620945791825,18.453186587453644,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.3620945791825,18.453186587453644,0), FreeCAD.Vector(436.25289556042367,18.219601947106128,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.25289556042367,18.219601947106128,0), FreeCAD.Vector(436.1450607916761,17.98601730675861,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.1450607916761,17.98601730675861,0), FreeCAD.Vector(436.03859128509964,17.752432666411096,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(436.03859128509964,17.752432666411096,0), FreeCAD.Vector(435.93348804102214,17.51884802606358,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.93348804102214,17.51884802606358,0), FreeCAD.Vector(435.8297520478933,17.285263385716064,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.8297520478933,17.285263385716064,0), FreeCAD.Vector(435.72738428224005,17.051678745368548,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.72738428224005,17.051678745368548,0), FreeCAD.Vector(435.6263857086208,16.818094105021032,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.6263857086208,16.818094105021032,0), FreeCAD.Vector(435.5267572795816,16.584509464673516,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.5267572795816,16.584509464673516,0), FreeCAD.Vector(435.4284999356123,16.350924824326,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.4284999356123,16.350924824326,0), FreeCAD.Vector(435.331614605103,16.117340183978484,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.331614605103,16.117340183978484,0), FreeCAD.Vector(435.2361022043011,15.88375554363097,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.2361022043011,15.88375554363097,0), FreeCAD.Vector(435.1419636372688,15.650170903283456,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.1419636372688,15.650170903283456,0), FreeCAD.Vector(435.04919979584133,15.416586262935942,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(435.04919979584133,15.416586262935942,0), FreeCAD.Vector(434.95781155958576,15.183001622588428,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.95781155958576,15.183001622588428,0), FreeCAD.Vector(434.8677997957594,14.949416982240914,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.8677997957594,14.949416982240914,0), FreeCAD.Vector(434.7791653592704,14.7158323418934,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.7791653592704,14.7158323418934,0), FreeCAD.Vector(434.691909092637,14.482247701545885,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.691909092637,14.482247701545885,0), FreeCAD.Vector(434.6060318259483,14.248663061198371,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.6060318259483,14.248663061198371,0), FreeCAD.Vector(434.52153437682654,14.015078420850857,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.52153437682654,14.015078420850857,0), FreeCAD.Vector(434.4384175503871,13.781493780503343,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.4384175503871,13.781493780503343,0), FreeCAD.Vector(434.35668213920195,13.547909140155829,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.35668213920195,13.547909140155829,0), FreeCAD.Vector(434.27632892326227,13.314324499808315,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.27632892326227,13.314324499808315,0), FreeCAD.Vector(434.1973586699413,13.0807398594608,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.1973586699413,13.0807398594608,0), FreeCAD.Vector(434.1197721339587,12.847155219113287,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.1197721339587,12.847155219113287,0), FreeCAD.Vector(434.04357005734494,12.613570578765772,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(434.04357005734494,12.613570578765772,0), FreeCAD.Vector(433.9687531694059,12.379985938418258,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.9687531694059,12.379985938418258,0), FreeCAD.Vector(433.895322186689,12.146401298070744,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.895322186689,12.146401298070744,0), FreeCAD.Vector(433.82327781294885,11.91281665772323,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.82327781294885,11.91281665772323,0), FreeCAD.Vector(433.75262073911404,11.679232017375716,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.75262073911404,11.679232017375716,0), FreeCAD.Vector(433.68335164325487,11.445647377028202,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.68335164325487,11.445647377028202,0), FreeCAD.Vector(433.61547119054995,11.212062736680688,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.61547119054995,11.212062736680688,0), FreeCAD.Vector(433.5489800332562,10.978478096333173,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.5489800332562,10.978478096333173,0), FreeCAD.Vector(433.4838788106765,10.74489345598566,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.4838788106765,10.74489345598566,0), FreeCAD.Vector(433.4201681491303,10.511308815638145,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.4201681491303,10.511308815638145,0), FreeCAD.Vector(433.3578486619225,10.277724175290631,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.3578486619225,10.277724175290631,0), FreeCAD.Vector(433.2969209493158,10.044139534943117,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.2969209493158,10.044139534943117,0), FreeCAD.Vector(433.23738559850057,9.810554894595603,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.23738559850057,9.810554894595603,0), FreeCAD.Vector(433.17924318356796,9.576970254248089,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.17924318356796,9.576970254248089,0), FreeCAD.Vector(433.12249426548124,9.343385613900574,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.12249426548124,9.343385613900574,0), FreeCAD.Vector(433.06713939205025,9.10980097355306,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.06713939205025,9.10980097355306,0), FreeCAD.Vector(433.01317909790407,8.876216333205546,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(433.01317909790407,8.876216333205546,0), FreeCAD.Vector(432.960613904466,8.642631692858032,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.960613904466,8.642631692858032,0), FreeCAD.Vector(432.9094443199281,8.409047052510518,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.9094443199281,8.409047052510518,0), FreeCAD.Vector(432.85967083922753,8.175462412163004,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.85967083922753,8.175462412163004,0), FreeCAD.Vector(432.81129394402154,7.94187777181549,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.81129394402154,7.94187777181549,0), FreeCAD.Vector(432.7643141026654,7.7082931314679755,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.7643141026654,7.7082931314679755,0), FreeCAD.Vector(432.7187317701895,7.474708491120461,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.7187317701895,7.474708491120461,0), FreeCAD.Vector(432.67454738827695,7.241123850772947,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.67454738827695,7.241123850772947,0), FreeCAD.Vector(432.6317613852431,7.007539210425433,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.6317613852431,7.007539210425433,0), FreeCAD.Vector(432.5903741760142,6.773954570077919,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.5903741760142,6.773954570077919,0), FreeCAD.Vector(432.5503861621076,6.540369929730405,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.5503861621076,6.540369929730405,0), FreeCAD.Vector(432.51179773161255,6.306785289382891,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.51179773161255,6.306785289382891,0), FreeCAD.Vector(432.474609259171,6.0732006490353765,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.474609259171,6.0732006490353765,0), FreeCAD.Vector(432.4388211059599,5.839616008687862,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.4388211059599,5.839616008687862,0), FreeCAD.Vector(432.4044336196735,5.606031368340348,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.4044336196735,5.606031368340348,0), FreeCAD.Vector(432.3714471345065,5.372446727992834,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.3714471345065,5.372446727992834,0), FreeCAD.Vector(432.33986197113774,5.13886208764532,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.33986197113774,5.13886208764532,0), FreeCAD.Vector(432.3096784367151,4.905277447297806,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.3096784367151,4.905277447297806,0), FreeCAD.Vector(432.28089682483994,4.671692806950292,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.28089682483994,4.671692806950292,0), FreeCAD.Vector(432.2535174155537,4.4381081666027775,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.2535174155537,4.4381081666027775,0), FreeCAD.Vector(432.2275404753233,4.204523526255263,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.2275404753233,4.204523526255263,0), FreeCAD.Vector(432.202966257029,3.970938885907749,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.202966257029,3.970938885907749,0), FreeCAD.Vector(432.1797949999517,3.737354245560234,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.1797949999517,3.737354245560234,0), FreeCAD.Vector(432.15802692976155,3.5037696052127196,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.15802692976155,3.5037696052127196,0), FreeCAD.Vector(432.13766225850657,3.270184964865205,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.13766225850657,3.270184964865205,0), FreeCAD.Vector(432.11870118460297,3.0366003245176905,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.11870118460297,3.0366003245176905,0), FreeCAD.Vector(432.1011438928248,2.803015684170176,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.1011438928248,2.803015684170176,0), FreeCAD.Vector(432.0849905542955,2.5694310438226613,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.0849905542955,2.5694310438226613,0), FreeCAD.Vector(432.0702413264792,2.3358464034751467,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.0702413264792,2.3358464034751467,0), FreeCAD.Vector(432.05689635317344,2.102261763127632,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.05689635317344,2.102261763127632,0), FreeCAD.Vector(432.04495576450154,1.8686771227801175,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.04495576450154,1.8686771227801175,0), FreeCAD.Vector(432.03441967690696,1.635092482432603,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.03441967690696,1.635092482432603,0), FreeCAD.Vector(432.0252881931472,1.4015078420850884,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.0252881931472,1.4015078420850884,0), FreeCAD.Vector(432.0175614022889,1.1679232017375738,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.0175614022889,1.1679232017375738,0), FreeCAD.Vector(432.01123937970357,0.9343385613900593,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.01123937970357,0.9343385613900593,0), FreeCAD.Vector(432.00632218706363,0.7007539210425449,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.00632218706363,0.7007539210425449,0), FreeCAD.Vector(432.00280987233975,0.4671692806950304,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.00280987233975,0.4671692806950304,0), FreeCAD.Vector(432.00070246979834,0.23358464034751591,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.00070246979834,0.23358464034751591,0), FreeCAD.Vector(432.0,1.4432899320127035e-15,0)))
    qwm_doc.sketch_subref.addGeometry(Part.LineSegment(FreeCAD.Vector(432.0,1.4432899320127035e-15,0), FreeCAD.Vector(432.0,0.0,0)))
    qwm_doc.addObject("Part::Extrusion", "subref")
    qwm_doc.subref.Base = qwm_doc.sketch_subref
    qwm_doc.subref.Dir = (0, 0, 1.0)
    qwm_doc.subref.Solid = True
    subref_viewObject = qwm_doc.subref.ViewObject
    subref_viewObject.Transparency = 60
    qwm_doc.subref.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_waveguide')
    qwm_doc.sketch_waveguide.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_waveguide.addGeometry(Part.LineSegment(FreeCAD.Vector(-20.0,20.0,0), FreeCAD.Vector(10.0,20.0,0)))
    qwm_doc.sketch_waveguide.addGeometry(Part.LineSegment(FreeCAD.Vector(10.0,20.0,0), FreeCAD.Vector(42.7085261848414,30.0,0)))
    qwm_doc.sketch_waveguide.addGeometry(Part.LineSegment(FreeCAD.Vector(42.7085261848414,30.0,0), FreeCAD.Vector(42.7085261848414,32.0,0)))
    qwm_doc.sketch_waveguide.addGeometry(Part.LineSegment(FreeCAD.Vector(42.7085261848414,32.0,0), FreeCAD.Vector(10.0,22.0,0)))
    qwm_doc.sketch_waveguide.addGeometry(Part.LineSegment(FreeCAD.Vector(10.0,22.0,0), FreeCAD.Vector(-20.0,22.0,0)))
    qwm_doc.sketch_waveguide.addGeometry(Part.LineSegment(FreeCAD.Vector(-20.0,22.0,0), FreeCAD.Vector(-20.0,20.0,0)))
    qwm_doc.addObject("Part::Extrusion", "waveguide")
    qwm_doc.waveguide.Base = qwm_doc.sketch_waveguide
    qwm_doc.waveguide.Dir = (0, 0, 1.0)
    qwm_doc.waveguide.Solid = True
    waveguide_viewObject = qwm_doc.waveguide.ViewObject
    waveguide_viewObject.Transparency = 60
    qwm_doc.waveguide.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_reflectpar')
    qwm_doc.sketch_reflectpar.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,0.0,0), FreeCAD.Vector(2.0,0.0,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.0,0.0,0), FreeCAD.Vector(2.06707051002595,10.999781819964143,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.06707051002595,10.999781819964143,0), FreeCAD.Vector(2.150908647558387,16.499672729946216,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.150908647558387,16.499672729946216,0), FreeCAD.Vector(2.2682820401037995,21.999563639928287,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.2682820401037995,21.999563639928287,0), FreeCAD.Vector(2.419190687662187,27.499454549910357,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.419190687662187,27.499454549910357,0), FreeCAD.Vector(2.6036345902335496,32.99934545989243,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.6036345902335496,32.99934545989243,0), FreeCAD.Vector(2.821613747817887,38.4992363698745,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.821613747817887,38.4992363698745,0), FreeCAD.Vector(3.073128160415199,43.99912727985657,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(3.073128160415199,43.99912727985657,0), FreeCAD.Vector(3.358177828025486,49.499018189838644,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(3.358177828025486,49.499018189838644,0), FreeCAD.Vector(3.6767627506487486,54.998909099820715,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(3.6767627506487486,54.998909099820715,0), FreeCAD.Vector(4.028882928284986,60.498800009802785,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(4.028882928284986,60.498800009802785,0), FreeCAD.Vector(4.414538360934198,65.99869091978486,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(4.414538360934198,65.99869091978486,0), FreeCAD.Vector(4.8337290485963855,71.49858182976693,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(4.8337290485963855,71.49858182976693,0), FreeCAD.Vector(5.286454991271547,76.998472739749,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(5.286454991271547,76.998472739749,0), FreeCAD.Vector(5.772716188959684,82.49836364973108,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(5.772716188959684,82.49836364973108,0), FreeCAD.Vector(6.292512641660796,87.99825455971315,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(6.292512641660796,87.99825455971315,0), FreeCAD.Vector(6.845844349374883,93.49814546969522,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(6.845844349374883,93.49814546969522,0), FreeCAD.Vector(7.432711312101945,98.99803637967729,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(7.432711312101945,98.99803637967729,0), FreeCAD.Vector(8.05311352984198,104.49792728965936,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(8.05311352984198,104.49792728965936,0), FreeCAD.Vector(8.707051002594994,109.99781819964143,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(8.707051002594994,109.99781819964143,0), FreeCAD.Vector(9.39452373036098,115.4977091096235,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(9.39452373036098,115.4977091096235,0), FreeCAD.Vector(10.115531713139942,120.99760001960557,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(10.115531713139942,120.99760001960557,0), FreeCAD.Vector(10.870074950931878,126.49749092958764,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(10.870074950931878,126.49749092958764,0), FreeCAD.Vector(11.658153443736792,131.99738183956973,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(11.658153443736792,131.99738183956973,0), FreeCAD.Vector(12.479767191554679,137.4972727495518,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(12.479767191554679,137.4972727495518,0), FreeCAD.Vector(13.33491619438554,142.99716365953387,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(13.33491619438554,142.99716365953387,0), FreeCAD.Vector(14.223600452229375,148.49705456951594,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(14.223600452229375,148.49705456951594,0), FreeCAD.Vector(15.145819965086186,153.996945479498,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(15.145819965086186,153.996945479498,0), FreeCAD.Vector(16.101574732955974,159.49683638948008,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(16.101574732955974,159.49683638948008,0), FreeCAD.Vector(17.090864755838737,164.99672729946215,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(17.090864755838737,164.99672729946215,0), FreeCAD.Vector(18.11369003373447,170.49661820944422,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(18.11369003373447,170.49661820944422,0), FreeCAD.Vector(19.170050566643184,175.9965091194263,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(19.170050566643184,175.9965091194263,0), FreeCAD.Vector(20.25994635456487,181.49640002940836,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(20.25994635456487,181.49640002940836,0), FreeCAD.Vector(21.383377397499533,186.99629093939043,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(21.383377397499533,186.99629093939043,0), FreeCAD.Vector(22.540343695447167,192.4961818493725,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(22.540343695447167,192.4961818493725,0), FreeCAD.Vector(23.73084524840778,197.99607275935458,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(23.73084524840778,197.99607275935458,0), FreeCAD.Vector(24.954882056381365,203.49596366933665,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(24.954882056381365,203.49596366933665,0), FreeCAD.Vector(26.212454119367923,208.99585457931872,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(26.212454119367923,208.99585457931872,0), FreeCAD.Vector(27.50356143736746,214.4957454893008,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(27.50356143736746,214.4957454893008,0), FreeCAD.Vector(28.828204010379974,219.99563639928286,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(28.828204010379974,219.99563639928286,0), FreeCAD.Vector(30.18638183840546,225.49552730926493,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(30.18638183840546,225.49552730926493,0), FreeCAD.Vector(31.578094921443917,230.995418219247,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(31.578094921443917,230.995418219247,0), FreeCAD.Vector(33.00334325949535,236.49530912922907,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(33.00334325949535,236.49530912922907,0), FreeCAD.Vector(34.46212685255977,241.99520003921114,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(34.46212685255977,241.99520003921114,0), FreeCAD.Vector(35.95444570063715,247.4950909491932,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(35.95444570063715,247.4950909491932,0), FreeCAD.Vector(37.48029980372751,252.99498185917528,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(37.48029980372751,252.99498185917528,0), FreeCAD.Vector(39.03968916183086,258.4948727691574,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(39.03968916183086,258.4948727691574,0), FreeCAD.Vector(40.63261377494717,263.99476367913945,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(40.63261377494717,263.99476367913945,0), FreeCAD.Vector(42.259073643076455,269.4946545891215,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(42.259073643076455,269.4946545891215,0), FreeCAD.Vector(43.919068766218714,274.9945454991036,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(43.919068766218714,274.9945454991036,0), FreeCAD.Vector(45.612599144373945,280.49443640908567,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(45.612599144373945,280.49443640908567,0), FreeCAD.Vector(47.33966477754216,285.99432731906774,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(47.33966477754216,285.99432731906774,0), FreeCAD.Vector(49.10026566572334,291.4942182290498,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(49.10026566572334,291.4942182290498,0), FreeCAD.Vector(50.8944018089175,296.9941091390319,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(50.8944018089175,296.9941091390319,0), FreeCAD.Vector(52.722073207124645,302.49400004901395,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(52.722073207124645,302.49400004901395,0), FreeCAD.Vector(54.583279860344746,307.993890958996,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(54.583279860344746,307.993890958996,0), FreeCAD.Vector(56.47802176857783,313.4937818689781,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(56.47802176857783,313.4937818689781,0), FreeCAD.Vector(58.40629893182389,318.99367277896016,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(58.40629893182389,318.99367277896016,0), FreeCAD.Vector(60.368111350082934,324.49356368894223,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(60.368111350082934,324.49356368894223,0), FreeCAD.Vector(62.36345902335494,329.9934545989243,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(62.36345902335494,329.9934545989243,0), FreeCAD.Vector(64.39234195163992,335.4933455089064,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(64.39234195163992,335.4933455089064,0), FreeCAD.Vector(66.45476013493789,340.99323641888844,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(66.45476013493789,340.99323641888844,0), FreeCAD.Vector(68.55071357324883,346.4931273288705,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(68.55071357324883,346.4931273288705,0), FreeCAD.Vector(70.68020226657273,351.9930182388526,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(70.68020226657273,351.9930182388526,0), FreeCAD.Vector(72.84322621490962,357.49290914883466,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(72.84322621490962,357.49290914883466,0), FreeCAD.Vector(75.03978541825948,362.9928000588167,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(75.03978541825948,362.9928000588167,0), FreeCAD.Vector(77.2698798766223,368.4926909687988,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(77.2698798766223,368.4926909687988,0), FreeCAD.Vector(79.53350958999813,373.99258187878087,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(79.53350958999813,373.99258187878087,0), FreeCAD.Vector(81.8306745583869,379.49247278876294,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(81.8306745583869,379.49247278876294,0), FreeCAD.Vector(84.16137478178867,384.992363698745,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(84.16137478178867,384.992363698745,0), FreeCAD.Vector(86.52561026020341,390.4922546087271,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(86.52561026020341,390.4922546087271,0), FreeCAD.Vector(88.92338099363111,395.99214551870915,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(88.92338099363111,395.99214551870915,0), FreeCAD.Vector(91.35468698207178,401.4920364286912,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(91.35468698207178,401.4920364286912,0), FreeCAD.Vector(93.81952822552546,406.9919273386733,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(93.81952822552546,406.9919273386733,0), FreeCAD.Vector(96.31790472399209,412.49181824865536,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(96.31790472399209,412.49181824865536,0), FreeCAD.Vector(98.84981647747169,417.99170915863743,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(98.84981647747169,417.99170915863743,0), FreeCAD.Vector(101.41526348596429,423.4916000686195,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(101.41526348596429,423.4916000686195,0), FreeCAD.Vector(104.01424574946984,428.9914909786016,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(104.01424574946984,428.9914909786016,0), FreeCAD.Vector(106.64676326798838,434.49138188858365,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(106.64676326798838,434.49138188858365,0), FreeCAD.Vector(109.3128160415199,439.9912727985657,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(109.3128160415199,439.9912727985657,0), FreeCAD.Vector(112.01240407006438,445.4911637085478,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(112.01240407006438,445.4911637085478,0), FreeCAD.Vector(114.74552735362184,450.99105461852986,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(114.74552735362184,450.99105461852986,0), FreeCAD.Vector(117.51218589219226,456.49094552851193,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(117.51218589219226,456.49094552851193,0), FreeCAD.Vector(120.31237968577567,461.990836438494,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(120.31237968577567,461.990836438494,0), FreeCAD.Vector(123.14610873437206,467.49072734847607,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(123.14610873437206,467.49072734847607,0), FreeCAD.Vector(126.01337303798141,472.99061825845814,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(126.01337303798141,472.99061825845814,0), FreeCAD.Vector(128.91417259660375,478.4905091684402,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(128.91417259660375,478.4905091684402,0), FreeCAD.Vector(131.84850741023908,483.9904000784223,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(131.84850741023908,483.9904000784223,0), FreeCAD.Vector(134.81637747888735,489.49029098840435,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(134.81637747888735,489.49029098840435,0), FreeCAD.Vector(137.8177828025486,494.9901818983864,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(137.8177828025486,494.9901818983864,0), FreeCAD.Vector(140.85272338122283,500.4900728083685,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(140.85272338122283,500.4900728083685,0), FreeCAD.Vector(143.92119921491005,505.98996371835057,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(143.92119921491005,505.98996371835057,0), FreeCAD.Vector(147.02321030361023,511.48985462833264,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(147.02321030361023,511.48985462833264,0), FreeCAD.Vector(150.15875664732343,516.9897455383148,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(150.15875664732343,516.9897455383148,0), FreeCAD.Vector(153.3278382460496,522.4896364482969,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(153.3278382460496,522.4896364482969,0), FreeCAD.Vector(156.53045509978872,527.989527358279,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(156.53045509978872,527.989527358279,0), FreeCAD.Vector(159.76660720854085,533.4894182682611,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(159.76660720854085,533.4894182682611,0), FreeCAD.Vector(163.03629457230596,538.9893091782433,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(163.03629457230596,538.9893091782433,0), FreeCAD.Vector(166.339517191084,544.4892000882254,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(166.339517191084,544.4892000882254,0), FreeCAD.Vector(169.67627506487506,549.9890909982075,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(169.67627506487506,549.9890909982075,0), FreeCAD.Vector(167.67627506487506,549.9890909982075,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(167.67627506487506,549.9890909982075,0), FreeCAD.Vector(164.339517191084,544.4892000882254,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(164.339517191084,544.4892000882254,0), FreeCAD.Vector(161.03629457230596,538.9893091782433,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(161.03629457230596,538.9893091782433,0), FreeCAD.Vector(157.76660720854085,533.4894182682611,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(157.76660720854085,533.4894182682611,0), FreeCAD.Vector(154.53045509978872,527.989527358279,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(154.53045509978872,527.989527358279,0), FreeCAD.Vector(151.3278382460496,522.4896364482969,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(151.3278382460496,522.4896364482969,0), FreeCAD.Vector(148.15875664732343,516.9897455383148,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(148.15875664732343,516.9897455383148,0), FreeCAD.Vector(145.02321030361026,511.4898546283327,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(145.02321030361026,511.4898546283327,0), FreeCAD.Vector(141.92119921491008,505.9899637183506,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(141.92119921491008,505.9899637183506,0), FreeCAD.Vector(138.85272338122286,500.49007280836855,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(138.85272338122286,500.49007280836855,0), FreeCAD.Vector(135.81778280254863,494.9901818983865,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(135.81778280254863,494.9901818983865,0), FreeCAD.Vector(132.81637747888738,489.4902909884044,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(132.81637747888738,489.4902909884044,0), FreeCAD.Vector(129.84850741023908,483.99040007842234,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(129.84850741023908,483.99040007842234,0), FreeCAD.Vector(126.91417259660378,478.49050916844027,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(126.91417259660378,478.49050916844027,0), FreeCAD.Vector(124.01337303798145,472.9906182584582,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(124.01337303798145,472.9906182584582,0), FreeCAD.Vector(121.14610873437208,467.4907273484761,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(121.14610873437208,467.4907273484761,0), FreeCAD.Vector(118.3123796857757,461.99083643849406,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(118.3123796857757,461.99083643849406,0), FreeCAD.Vector(115.51218589219229,456.490945528512,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(115.51218589219229,456.490945528512,0), FreeCAD.Vector(112.74552735362187,450.9910546185299,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(112.74552735362187,450.9910546185299,0), FreeCAD.Vector(110.01240407006439,445.49116370854784,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(110.01240407006439,445.49116370854784,0), FreeCAD.Vector(107.31281604151992,439.9912727985658,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(107.31281604151992,439.9912727985658,0), FreeCAD.Vector(104.6467632679884,434.4913818885837,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(104.6467632679884,434.4913818885837,0), FreeCAD.Vector(102.01424574946986,428.99149097860163,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(102.01424574946986,428.99149097860163,0), FreeCAD.Vector(99.4152634859643,423.49160006861956,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(99.4152634859643,423.49160006861956,0), FreeCAD.Vector(96.84981647747173,417.9917091586375,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(96.84981647747173,417.9917091586375,0), FreeCAD.Vector(94.31790472399211,412.4918182486554,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(94.31790472399211,412.4918182486554,0), FreeCAD.Vector(91.81952822552547,406.99192733867335,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(91.81952822552547,406.99192733867335,0), FreeCAD.Vector(89.35468698207183,401.4920364286913,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(89.35468698207183,401.4920364286913,0), FreeCAD.Vector(86.92338099363114,395.9921455187092,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(86.92338099363114,395.9921455187092,0), FreeCAD.Vector(84.52561026020344,390.49225460872714,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(84.52561026020344,390.49225460872714,0), FreeCAD.Vector(82.16137478178868,384.99236369874507,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(82.16137478178868,384.99236369874507,0), FreeCAD.Vector(79.83067455838692,379.492472788763,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(79.83067455838692,379.492472788763,0), FreeCAD.Vector(77.53350958999815,373.9925818787809,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(77.53350958999815,373.9925818787809,0), FreeCAD.Vector(75.26987987662234,368.49269096879885,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(75.26987987662234,368.49269096879885,0), FreeCAD.Vector(73.0397854182595,362.9928000588168,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(73.0397854182595,362.9928000588168,0), FreeCAD.Vector(70.84322621490965,357.4929091488347,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(70.84322621490965,357.4929091488347,0), FreeCAD.Vector(68.68020226657276,351.99301823885264,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(68.68020226657276,351.99301823885264,0), FreeCAD.Vector(66.55071357324884,346.49312732887057,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(66.55071357324884,346.49312732887057,0), FreeCAD.Vector(64.45476013493791,340.9932364188885,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(64.45476013493791,340.9932364188885,0), FreeCAD.Vector(62.39234195163995,335.49334550890643,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(62.39234195163995,335.49334550890643,0), FreeCAD.Vector(60.36345902335496,329.99345459892436,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(60.36345902335496,329.99345459892436,0), FreeCAD.Vector(58.36811135008295,324.4935636889423,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(58.36811135008295,324.4935636889423,0), FreeCAD.Vector(56.40629893182392,318.9936727789602,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(56.40629893182392,318.9936727789602,0), FreeCAD.Vector(54.478021768577854,313.49378186897815,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(54.478021768577854,313.49378186897815,0), FreeCAD.Vector(52.583279860344774,307.9938909589961,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(52.583279860344774,307.9938909589961,0), FreeCAD.Vector(50.72207320712466,302.494000049014,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(50.72207320712466,302.494000049014,0), FreeCAD.Vector(48.89440180891752,296.99410913903193,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(48.89440180891752,296.99410913903193,0), FreeCAD.Vector(47.100265665723356,291.49421822904986,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(47.100265665723356,291.49421822904986,0), FreeCAD.Vector(45.339664777542176,285.9943273190678,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(45.339664777542176,285.9943273190678,0), FreeCAD.Vector(43.61259914437397,280.4944364090857,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(43.61259914437397,280.4944364090857,0), FreeCAD.Vector(41.91906876621873,274.99454549910365,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(41.91906876621873,274.99454549910365,0), FreeCAD.Vector(40.25907364307647,269.4946545891216,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(40.25907364307647,269.4946545891216,0), FreeCAD.Vector(38.63261377494718,263.9947636791395,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(38.63261377494718,263.9947636791395,0), FreeCAD.Vector(37.03968916183087,258.49487276915744,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(37.03968916183087,258.49487276915744,0), FreeCAD.Vector(35.48029980372754,252.99498185917537,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(35.48029980372754,252.99498185917537,0), FreeCAD.Vector(33.95444570063717,247.4950909491933,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(33.95444570063717,247.4950909491933,0), FreeCAD.Vector(32.462126852559784,241.99520003921123,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(32.462126852559784,241.99520003921123,0), FreeCAD.Vector(31.003343259495377,236.49530912922916,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(31.003343259495377,236.49530912922916,0), FreeCAD.Vector(29.57809492144394,230.99541821924709,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(29.57809492144394,230.99541821924709,0), FreeCAD.Vector(28.186381838405477,225.49552730926501,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(28.186381838405477,225.49552730926501,0), FreeCAD.Vector(26.82820401037999,219.99563639928294,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(26.82820401037999,219.99563639928294,0), FreeCAD.Vector(25.50356143736748,214.49574548930087,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(25.50356143736748,214.49574548930087,0), FreeCAD.Vector(24.212454119367944,208.9958545793188,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(24.212454119367944,208.9958545793188,0), FreeCAD.Vector(22.954882056381383,203.49596366933673,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(22.954882056381383,203.49596366933673,0), FreeCAD.Vector(21.730845248407796,197.99607275935466,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(21.730845248407796,197.99607275935466,0), FreeCAD.Vector(20.540343695447184,192.4961818493726,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(20.540343695447184,192.4961818493726,0), FreeCAD.Vector(19.383377397499547,186.99629093939052,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(19.383377397499547,186.99629093939052,0), FreeCAD.Vector(18.259946354564885,181.49640002940845,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(18.259946354564885,181.49640002940845,0), FreeCAD.Vector(17.170050566643198,175.99650911942638,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(17.170050566643198,175.99650911942638,0), FreeCAD.Vector(16.11369003373449,170.4966182094443,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(16.11369003373449,170.4966182094443,0), FreeCAD.Vector(15.090864755838751,164.99672729946224,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(15.090864755838751,164.99672729946224,0), FreeCAD.Vector(14.10157473295599,159.49683638948017,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(14.10157473295599,159.49683638948017,0), FreeCAD.Vector(13.1458199650862,153.9969454794981,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(13.1458199650862,153.9969454794981,0), FreeCAD.Vector(12.22360045222939,148.49705456951602,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(12.22360045222939,148.49705456951602,0), FreeCAD.Vector(11.334916194385555,142.99716365953395,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(11.334916194385555,142.99716365953395,0), FreeCAD.Vector(10.479767191554691,137.49727274955188,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(10.479767191554691,137.49727274955188,0), FreeCAD.Vector(9.658153443736802,131.9973818395698,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(9.658153443736802,131.9973818395698,0), FreeCAD.Vector(8.870074950931892,126.49749092958774,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(8.870074950931892,126.49749092958774,0), FreeCAD.Vector(8.115531713139955,120.99760001960567,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(8.115531713139955,120.99760001960567,0), FreeCAD.Vector(7.3945237303609925,115.4977091096236,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(7.3945237303609925,115.4977091096236,0), FreeCAD.Vector(6.707051002595005,109.99781819964153,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(6.707051002595005,109.99781819964153,0), FreeCAD.Vector(6.053113529841993,104.49792728965946,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(6.053113529841993,104.49792728965946,0), FreeCAD.Vector(5.432711312101955,98.99803637967739,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(5.432711312101955,98.99803637967739,0), FreeCAD.Vector(4.845844349374893,93.49814546969532,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(4.845844349374893,93.49814546969532,0), FreeCAD.Vector(4.292512641660806,87.99825455971325,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(4.292512641660806,87.99825455971325,0), FreeCAD.Vector(3.7727161889596927,82.49836364973117,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(3.7727161889596927,82.49836364973117,0), FreeCAD.Vector(3.2864549912715555,76.9984727397491,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(3.2864549912715555,76.9984727397491,0), FreeCAD.Vector(2.833729048596393,71.49858182976703,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.833729048596393,71.49858182976703,0), FreeCAD.Vector(2.4145383609342055,65.99869091978496,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.4145383609342055,65.99869091978496,0), FreeCAD.Vector(2.0288829282849923,60.49880000980289,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(2.0288829282849923,60.49880000980289,0), FreeCAD.Vector(1.6767627506487548,54.99890909982082,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(1.6767627506487548,54.99890909982082,0), FreeCAD.Vector(1.358177828025492,49.49901818983875,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(1.358177828025492,49.49901818983875,0), FreeCAD.Vector(1.073128160415204,43.99912727985668,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(1.073128160415204,43.99912727985668,0), FreeCAD.Vector(0.8216137478178912,38.49923636987461,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(0.8216137478178912,38.49923636987461,0), FreeCAD.Vector(0.6036345902335534,32.99934545989254,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(0.6036345902335534,32.99934545989254,0), FreeCAD.Vector(0.4191906876621904,27.499454549910467,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(0.4191906876621904,27.499454549910467,0), FreeCAD.Vector(0.2682820401038024,21.999563639928397,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(0.2682820401038024,21.999563639928397,0), FreeCAD.Vector(0.15090864755838937,16.499672729946326,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(0.15090864755838937,16.499672729946326,0), FreeCAD.Vector(0.0670705100259513,10.999781819964255,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0670705100259513,10.999781819964255,0), FreeCAD.Vector(0.016767627506488164,5.4998909099821836,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(0.016767627506488164,5.4998909099821836,0), FreeCAD.Vector(6.94232579339733e-30,1.1191048088221578e-13,0)))
    qwm_doc.sketch_reflectpar.addGeometry(Part.LineSegment(FreeCAD.Vector(6.94232579339733e-30,1.1191048088221578e-13,0), FreeCAD.Vector(0.0,0.0,0)))
    qwm_doc.addObject("Part::Extrusion", "reflectpar")
    qwm_doc.reflectpar.Base = qwm_doc.sketch_reflectpar
    qwm_doc.reflectpar.Dir = (0, 0, 1.0)
    qwm_doc.reflectpar.Solid = True
    reflectpar_viewObject = qwm_doc.reflectpar.ViewObject
    reflectpar_viewObject.Transparency = 60
    qwm_doc.reflectpar.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_airopening')
    qwm_doc.sketch_airopening.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_airopening.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,0.0,0), FreeCAD.Vector(4.0,0.0,0)))
    qwm_doc.sketch_airopening.addGeometry(Part.LineSegment(FreeCAD.Vector(4.0,0.0,0), FreeCAD.Vector(4.0,22.0,0)))
    qwm_doc.sketch_airopening.addGeometry(Part.LineSegment(FreeCAD.Vector(4.0,22.0,0), FreeCAD.Vector(0.0,22.0,0)))
    qwm_doc.sketch_airopening.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,22.0,0), FreeCAD.Vector(0.0,0.0,0)))
    qwm_doc.addObject("Part::Extrusion", "airopening")
    qwm_doc.airopening.Base = qwm_doc.sketch_airopening
    qwm_doc.airopening.Dir = (0, 0, 1.0)
    qwm_doc.airopening.Solid = True
    airopening_viewObject = qwm_doc.airopening.ViewObject
    airopening_viewObject.Transparency = 60
    qwm_doc.airopening.Medium = QW_Modeller.getQWMedium("air")
    qwm_doc.addObject("Part::Cut","Cut1")
    qwm_doc.Cut1.Base = qwm_doc.reflectpar
    qwm_doc.Cut1.Tool = qwm_doc.airopening
    qwm_doc.Cut1.Medium = qwm_doc.airopening.Medium
    FreeCAD.Gui.activeDocument().hide('airopening')
    FreeCAD.Gui.activeDocument().hide('reflectpar')
