
import FreeCAD
import FreeCADGui
from FreeCAD import Base
import QW_Modeller
from qw_project import *
import Part
import Sketcher
from qw_units import *
from qw_paths import *

setGHzBaseFreqUnit()
setmmBaseGeomUnit()

def set_GeometryAndMedia(qwm_doc):
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_cwghwg')
    qwm_doc.sketch_cwghwg.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(50.0,0.0,0), FreeCAD.Vector(49.75923633360985,4.90085701647803,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(49.75923633360985,4.90085701647803,0), FreeCAD.Vector(49.039264020161525,9.754516100806413,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(49.039264020161525,9.754516100806413,0), FreeCAD.Vector(47.84701678661044,14.514233862723117,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(47.84701678661044,14.514233862723117,0), FreeCAD.Vector(46.19397662556434,19.134171618254488,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(46.19397662556434,19.134171618254488,0), FreeCAD.Vector(44.09606321741775,23.56983684129988,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(44.09606321741775,23.56983684129988,0), FreeCAD.Vector(41.57348061512726,27.778511650980107,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(41.57348061512726,27.778511650980107,0), FreeCAD.Vector(38.65052266813685,31.719664208182273,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(38.65052266813685,31.719664208182273,0), FreeCAD.Vector(35.35533905932738,35.35533905932738,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(35.35533905932738,35.35533905932738,0), FreeCAD.Vector(31.719664208182273,38.650522668136844,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(31.719664208182273,38.650522668136844,0), FreeCAD.Vector(27.778511650980114,41.57348061512726,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(27.778511650980114,41.57348061512726,0), FreeCAD.Vector(23.569836841299878,44.09606321741775,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(23.569836841299878,44.09606321741775,0), FreeCAD.Vector(19.13417161825449,46.19397662556434,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(19.13417161825449,46.19397662556434,0), FreeCAD.Vector(14.514233862723117,47.847016786610446,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(14.514233862723117,47.847016786610446,0), FreeCAD.Vector(9.754516100806416,49.039264020161525,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(9.754516100806416,49.039264020161525,0), FreeCAD.Vector(4.900857016478027,49.75923633360985,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(4.900857016478027,49.75923633360985,0), FreeCAD.Vector(3.061616997868383e-15,50.0,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(3.061616997868383e-15,50.0,0), FreeCAD.Vector(-4.9008570164780325,49.75923633360985,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-4.9008570164780325,49.75923633360985,0), FreeCAD.Vector(-9.75451610080641,49.039264020161525,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-9.75451610080641,49.039264020161525,0), FreeCAD.Vector(-14.514233862723119,47.84701678661044,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-14.514233862723119,47.84701678661044,0), FreeCAD.Vector(-19.134171618254488,46.19397662556434,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-19.134171618254488,46.19397662556434,0), FreeCAD.Vector(-23.569836841299885,44.09606321741775,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-23.569836841299885,44.09606321741775,0), FreeCAD.Vector(-27.778511650980114,41.57348061512726,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-27.778511650980114,41.57348061512726,0), FreeCAD.Vector(-31.71966420818227,38.65052266813686,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-31.71966420818227,38.65052266813686,0), FreeCAD.Vector(-35.35533905932737,35.35533905932738,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-35.35533905932737,35.35533905932738,0), FreeCAD.Vector(-38.65052266813685,31.719664208182273,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-38.65052266813685,31.719664208182273,0), FreeCAD.Vector(-41.573480615127266,27.778511650980107,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-41.573480615127266,27.778511650980107,0), FreeCAD.Vector(-44.09606321741775,23.56983684129989,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-44.09606321741775,23.56983684129989,0), FreeCAD.Vector(-46.19397662556434,19.134171618254495,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-46.19397662556434,19.134171618254495,0), FreeCAD.Vector(-47.84701678661044,14.514233862723119,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-47.84701678661044,14.514233862723119,0), FreeCAD.Vector(-49.039264020161525,9.754516100806407,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-49.039264020161525,9.754516100806407,0), FreeCAD.Vector(-49.75923633360984,4.900857016478041,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-49.75923633360984,4.900857016478041,0), FreeCAD.Vector(-50.0,6.123233995736766e-15,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-50.0,6.123233995736766e-15,0), FreeCAD.Vector(-49.75923633360985,-4.90085701647803,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-49.75923633360985,-4.90085701647803,0), FreeCAD.Vector(-49.039264020161525,-9.754516100806418,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-49.039264020161525,-9.754516100806418,0), FreeCAD.Vector(-47.847016786610446,-14.514233862723106,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-47.847016786610446,-14.514233862723106,0), FreeCAD.Vector(-46.19397662556434,-19.134171618254484,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-46.19397662556434,-19.134171618254484,0), FreeCAD.Vector(-44.09606321741775,-23.56983684129988,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-44.09606321741775,-23.56983684129988,0), FreeCAD.Vector(-41.57348061512726,-27.778511650980114,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-41.57348061512726,-27.778511650980114,0), FreeCAD.Vector(-38.65052266813686,-31.719664208182262,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-38.65052266813686,-31.719664208182262,0), FreeCAD.Vector(-35.355339059327385,-35.35533905932737,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-35.355339059327385,-35.35533905932737,0), FreeCAD.Vector(-31.719664208182298,-38.65052266813683,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-31.719664208182298,-38.65052266813683,0), FreeCAD.Vector(-27.778511650980107,-41.57348061512726,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-27.778511650980107,-41.57348061512726,0), FreeCAD.Vector(-23.569836841299892,-44.09606321741775,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-23.569836841299892,-44.09606321741775,0), FreeCAD.Vector(-19.134171618254474,-46.19397662556434,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-19.134171618254474,-46.19397662556434,0), FreeCAD.Vector(-14.514233862723122,-47.84701678661044,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-14.514233862723122,-47.84701678661044,0), FreeCAD.Vector(-9.754516100806434,-49.03926402016152,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-9.754516100806434,-49.03926402016152,0), FreeCAD.Vector(-4.900857016478023,-49.75923633360985,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-4.900857016478023,-49.75923633360985,0), FreeCAD.Vector(-9.184850993605149e-15,-50.0,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(-9.184850993605149e-15,-50.0,0), FreeCAD.Vector(4.900857016478004,-49.75923633360985,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(4.900857016478004,-49.75923633360985,0), FreeCAD.Vector(9.754516100806415,-49.039264020161525,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(9.754516100806415,-49.039264020161525,0), FreeCAD.Vector(14.514233862723103,-47.847016786610446,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(14.514233862723103,-47.847016786610446,0), FreeCAD.Vector(19.1341716182545,-46.19397662556433,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(19.1341716182545,-46.19397662556433,0), FreeCAD.Vector(23.569836841299878,-44.09606321741775,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(23.569836841299878,-44.09606321741775,0), FreeCAD.Vector(27.778511650980093,-41.57348061512727,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(27.778511650980093,-41.57348061512727,0), FreeCAD.Vector(31.71966420818228,-38.650522668136844,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(31.71966420818228,-38.650522668136844,0), FreeCAD.Vector(35.35533905932737,-35.355339059327385,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(35.35533905932737,-35.355339059327385,0), FreeCAD.Vector(38.65052266813686,-31.719664208182262,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(38.65052266813686,-31.719664208182262,0), FreeCAD.Vector(41.57348061512726,-27.778511650980107,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(41.57348061512726,-27.778511650980107,0), FreeCAD.Vector(44.09606321741774,-23.569836841299896,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(44.09606321741774,-23.569836841299896,0), FreeCAD.Vector(46.19397662556434,-19.134171618254477,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(46.19397662556434,-19.134171618254477,0), FreeCAD.Vector(47.84701678661044,-14.514233862723124,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(47.84701678661044,-14.514233862723124,0), FreeCAD.Vector(49.03926402016152,-9.754516100806436,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(49.03926402016152,-9.754516100806436,0), FreeCAD.Vector(49.75923633360985,-4.900857016478025,0)))
    qwm_doc.sketch_cwghwg.addGeometry(Part.LineSegment(FreeCAD.Vector(49.75923633360985,-4.900857016478025,0), FreeCAD.Vector(50.0,0.0,0)))
    qwm_doc.addObject("Part::Extrusion", "cwghwg")
    qwm_doc.cwghwg.Base = qwm_doc.sketch_cwghwg
    qwm_doc.cwghwg.Dir = (0, 0, 300.0)
    qwm_doc.cwghwg.Solid = True
    cwghwg_viewObject = qwm_doc.cwghwg.ViewObject
    cwghwg_viewObject.Transparency = 60
    qwm_doc.cwghwg.Medium = QW_Modeller.getQWMedium("air")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_cwghld')
    qwm_doc.sketch_cwghld.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,100.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(15.0,0.0,0), FreeCAD.Vector(14.927770900082955,1.470257104943409,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(14.927770900082955,1.470257104943409,0), FreeCAD.Vector(14.711779206048456,2.9263548302419236,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(14.711779206048456,2.9263548302419236,0), FreeCAD.Vector(14.354105035983132,4.354270158816935,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(14.354105035983132,4.354270158816935,0), FreeCAD.Vector(13.858192987669302,5.740251485476347,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(13.858192987669302,5.740251485476347,0), FreeCAD.Vector(13.228818965225326,7.070951052389964,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(13.228818965225326,7.070951052389964,0), FreeCAD.Vector(12.472044184538179,8.333553495294034,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(12.472044184538179,8.333553495294034,0), FreeCAD.Vector(11.595156800441055,9.515899262454683,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(11.595156800441055,9.515899262454683,0), FreeCAD.Vector(10.606601717798213,10.606601717798213,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(10.606601717798213,10.606601717798213,0), FreeCAD.Vector(9.515899262454683,11.595156800441053,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(9.515899262454683,11.595156800441053,0), FreeCAD.Vector(8.333553495294034,12.472044184538179,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(8.333553495294034,12.472044184538179,0), FreeCAD.Vector(7.0709510523899635,13.228818965225326,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(7.0709510523899635,13.228818965225326,0), FreeCAD.Vector(5.740251485476348,13.858192987669302,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(5.740251485476348,13.858192987669302,0), FreeCAD.Vector(4.354270158816935,14.354105035983133,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(4.354270158816935,14.354105035983133,0), FreeCAD.Vector(2.926354830241925,14.711779206048456,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(2.926354830241925,14.711779206048456,0), FreeCAD.Vector(1.4702571049434083,14.927770900082955,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(1.4702571049434083,14.927770900082955,0), FreeCAD.Vector(9.18485099360515e-16,15.0,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(9.18485099360515e-16,15.0,0), FreeCAD.Vector(-1.4702571049434097,14.927770900082955,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-1.4702571049434097,14.927770900082955,0), FreeCAD.Vector(-2.926354830241923,14.711779206048456,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-2.926354830241923,14.711779206048456,0), FreeCAD.Vector(-4.354270158816936,14.354105035983132,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-4.354270158816936,14.354105035983132,0), FreeCAD.Vector(-5.740251485476346,13.858192987669302,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-5.740251485476346,13.858192987669302,0), FreeCAD.Vector(-7.070951052389965,13.228818965225326,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-7.070951052389965,13.228818965225326,0), FreeCAD.Vector(-8.333553495294034,12.472044184538177,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-8.333553495294034,12.472044184538177,0), FreeCAD.Vector(-9.515899262454681,11.595156800441057,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-9.515899262454681,11.595156800441057,0), FreeCAD.Vector(-10.606601717798211,10.606601717798213,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-10.606601717798211,10.606601717798213,0), FreeCAD.Vector(-11.595156800441055,9.515899262454683,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-11.595156800441055,9.515899262454683,0), FreeCAD.Vector(-12.47204418453818,8.333553495294034,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-12.47204418453818,8.333553495294034,0), FreeCAD.Vector(-13.228818965225324,7.070951052389967,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-13.228818965225324,7.070951052389967,0), FreeCAD.Vector(-13.858192987669302,5.740251485476349,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-13.858192987669302,5.740251485476349,0), FreeCAD.Vector(-14.354105035983132,4.354270158816936,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-14.354105035983132,4.354270158816936,0), FreeCAD.Vector(-14.711779206048456,2.9263548302419227,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-14.711779206048456,2.9263548302419227,0), FreeCAD.Vector(-14.927770900082953,1.4702571049434123,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-14.927770900082953,1.4702571049434123,0), FreeCAD.Vector(-15.0,1.83697019872103e-15,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-15.0,1.83697019872103e-15,0), FreeCAD.Vector(-14.927770900082955,-1.4702571049434088,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-14.927770900082955,-1.4702571049434088,0), FreeCAD.Vector(-14.711779206048456,-2.9263548302419253,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-14.711779206048456,-2.9263548302419253,0), FreeCAD.Vector(-14.354105035983133,-4.354270158816932,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-14.354105035983133,-4.354270158816932,0), FreeCAD.Vector(-13.858192987669304,-5.740251485476345,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-13.858192987669304,-5.740251485476345,0), FreeCAD.Vector(-13.228818965225326,-7.070951052389964,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-13.228818965225326,-7.070951052389964,0), FreeCAD.Vector(-12.472044184538179,-8.333553495294034,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-12.472044184538179,-8.333553495294034,0), FreeCAD.Vector(-11.595156800441057,-9.51589926245468,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-11.595156800441057,-9.51589926245468,0), FreeCAD.Vector(-10.606601717798215,-10.606601717798211,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-10.606601717798215,-10.606601717798211,0), FreeCAD.Vector(-9.515899262454688,-11.59515680044105,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-9.515899262454688,-11.59515680044105,0), FreeCAD.Vector(-8.333553495294034,-12.472044184538179,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-8.333553495294034,-12.472044184538179,0), FreeCAD.Vector(-7.070951052389968,-13.228818965225324,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-7.070951052389968,-13.228818965225324,0), FreeCAD.Vector(-5.7402514854763425,-13.858192987669304,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-5.7402514854763425,-13.858192987669304,0), FreeCAD.Vector(-4.354270158816937,-14.354105035983132,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-4.354270158816937,-14.354105035983132,0), FreeCAD.Vector(-2.9263548302419298,-14.711779206048455,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-2.9263548302419298,-14.711779206048455,0), FreeCAD.Vector(-1.4702571049434068,-14.927770900082955,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-1.4702571049434068,-14.927770900082955,0), FreeCAD.Vector(-2.7554552980815444e-15,-15.0,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(-2.7554552980815444e-15,-15.0,0), FreeCAD.Vector(1.4702571049434014,-14.927770900082955,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(1.4702571049434014,-14.927770900082955,0), FreeCAD.Vector(2.9263548302419244,-14.711779206048456,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(2.9263548302419244,-14.711779206048456,0), FreeCAD.Vector(4.354270158816931,-14.354105035983133,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(4.354270158816931,-14.354105035983133,0), FreeCAD.Vector(5.7402514854763504,-13.8581929876693,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(5.7402514854763504,-13.8581929876693,0), FreeCAD.Vector(7.0709510523899635,-13.228818965225326,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(7.0709510523899635,-13.228818965225326,0), FreeCAD.Vector(8.333553495294028,-12.472044184538182,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(8.333553495294028,-12.472044184538182,0), FreeCAD.Vector(9.515899262454685,-11.595156800441053,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(9.515899262454685,-11.595156800441053,0), FreeCAD.Vector(10.60660171779821,-10.606601717798215,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(10.60660171779821,-10.606601717798215,0), FreeCAD.Vector(11.595156800441059,-9.51589926245468,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(11.595156800441059,-9.51589926245468,0), FreeCAD.Vector(12.472044184538179,-8.333553495294034,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(12.472044184538179,-8.333553495294034,0), FreeCAD.Vector(13.228818965225322,-7.070951052389969,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(13.228818965225322,-7.070951052389969,0), FreeCAD.Vector(13.858192987669304,-5.740251485476343,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(13.858192987669304,-5.740251485476343,0), FreeCAD.Vector(14.354105035983132,-4.354270158816938,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(14.354105035983132,-4.354270158816938,0), FreeCAD.Vector(14.711779206048455,-2.9263548302419307,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(14.711779206048455,-2.9263548302419307,0), FreeCAD.Vector(14.927770900082955,-1.4702571049434077,0)))
    qwm_doc.sketch_cwghld.addGeometry(Part.LineSegment(FreeCAD.Vector(14.927770900082955,-1.4702571049434077,0), FreeCAD.Vector(15.0,0.0,0)))
    qwm_doc.addObject("Part::Extrusion", "cwghld")
    qwm_doc.cwghld.Base = qwm_doc.sketch_cwghld
    qwm_doc.cwghld.Dir = (0, 0, 100.0)
    qwm_doc.cwghld.Solid = True
    cwghld_viewObject = qwm_doc.cwghld.ViewObject
    cwghld_viewObject.Transparency = 60
    qwm_doc.cwghld.Medium = QW_Modeller.getQWMedium("air")
