
import FreeCAD
import FreeCADGui
from FreeCAD import Base
import QW_Modeller
from qw_project import *
import Part
import Sketcher
from qw_units import *
from qw_paths import *

setGHzBaseFreqUnit()
setmmBaseGeomUnit()

def set_GeometryAndMedia(qwm_doc):
    RD5870 = QW_Modeller.addQWMedium("RD5870")
    RD5870.materialtype = "Isotropic"
    RD5870.Eps = [2.06, 2.06, 2.06]
    RD5870.Mu = [1.0, 1.0, 1.0]
    RD5870.Sigma = [0.0, 0.0, 0.0]
    RD5870.SigmaM = [0.0, 0.0, 0.0]
    RD5870.density = 0.0
    RD5870.initemp = 20.0
    RD5870.specheat = 1.0
    RD5870.thermcond = [0.0,0.0,0.0]
    RD5870.mcolor_PENPARAMS = (0.0,0.5450980392156862,0.5450980392156862,0.0)
    RD5870.mstyle_PENPARAMS = 0
    RD5870.mwidth_PENPARAMS = 1
    RD5870.mpencolor_BRUSHPARAMS = (0.0,0.0,0.5019607843137255,0.0)
    RD5870.mbkcolor_BRUSHPARAMS = (0.3333333333333333,0.4196078431372549,0.1843137254901961,0.0)
    RD5870.mstyle_BRUSHPARAMS = 6
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_substrate')
    qwm_doc.sketch_substrate.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_substrate.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,0.0,0), FreeCAD.Vector(40.0,0.0,0)))
    qwm_doc.sketch_substrate.addGeometry(Part.LineSegment(FreeCAD.Vector(40.0,0.0,0), FreeCAD.Vector(40.0,90.0,0)))
    qwm_doc.sketch_substrate.addGeometry(Part.LineSegment(FreeCAD.Vector(40.0,90.0,0), FreeCAD.Vector(0.0,90.0,0)))
    qwm_doc.sketch_substrate.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,90.0,0), FreeCAD.Vector(0.0,0.0,0)))
    qwm_doc.addObject("Part::Extrusion", "substrate")
    qwm_doc.substrate.Base = qwm_doc.sketch_substrate
    qwm_doc.substrate.Dir = (0, 0, 3.1496)
    qwm_doc.substrate.Solid = True
    substrate_viewObject = qwm_doc.substrate.ViewObject
    substrate_viewObject.Transparency = 60
    qwm_doc.substrate.Medium = QW_Modeller.getQWMedium("RD5870")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_lflare')
    qwm_doc.sketch_lflare.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.5,41.5,0), FreeCAD.Vector(21.5,60.0,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.5,60.0,0), FreeCAD.Vector(21.489159105846554,61.47203022982254,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.489159105846554,61.47203022982254,0), FreeCAD.Vector(21.45666254004977,62.94051420988682,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.45666254004977,62.94051420988682,0), FreeCAD.Vector(21.402588589683027,64.40191423366085,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.402588589683027,64.40191423366085,0), FreeCAD.Vector(21.327067523629076,65.85270966048384,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.327067523629076,65.85270966048384,0), FreeCAD.Vector(21.230281278750894,67.28940539709791,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.230281278750894,67.28940539709791,0), FreeCAD.Vector(21.112463021589882,68.70854031763386,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.112463021589882,68.70854031763386,0), FreeCAD.Vector(20.973896586647186,70.1066956017666,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.973896586647186,70.1066956017666,0), FreeCAD.Vector(20.81491579260158,71.4805029709527,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.81491579260158,71.4805029709527,0), FreeCAD.Vector(20.63590363811099,72.82665280290846,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.63590363811099,72.82665280290846,0), FreeCAD.Vector(20.437291379135196,74.14190210477993,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.437291379135196,74.14190210477993,0), FreeCAD.Vector(20.219557490002448,75.42308232579666,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.219557490002448,75.42308232579666,0), FreeCAD.Vector(19.983226510722908,76.66710699058807,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(19.983226510722908,76.66710699058807,0), FreeCAD.Vector(19.728867783325803,77.870979134773,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(19.728867783325803,77.870979134773,0), FreeCAD.Vector(19.457094080264632,79.03179852490936,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(19.457094080264632,79.03179852490936,0), FreeCAD.Vector(19.16856012819463,80.14676864541056,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(19.16856012819463,80.14676864541056,0), FreeCAD.Vector(18.86396103067893,81.21320343559643,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.86396103067893,81.21320343559643,0), FreeCAD.Vector(18.544030593623166,82.22853376064877,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.544030593623166,82.22853376064877,0), FreeCAD.Vector(18.20953955747281,83.1903136008821,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.20953955747281,83.1903136008821,0), FreeCAD.Vector(17.8612937404319,84.09622594441934,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.8612937404319,84.09622594441934,0), FreeCAD.Vector(17.50013209717642,84.94408836907635,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.50013209717642,84.94408836907635,0), FreeCAD.Vector(17.126924697738996,85.73185830000816,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.126924697738996,85.73185830000816,0), FreeCAD.Vector(16.742570631433978,86.45763793045066,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(16.742570631433978,86.45763793045066,0), FreeCAD.Vector(16.34799584087254,87.1196787937033,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(16.34799584087254,87.1196787937033,0), FreeCAD.Vector(15.944150891285808,87.7163859753386,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.944150891285808,87.7163859753386,0), FreeCAD.Vector(15.53200868052998,88.24632195549063,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.53200868052998,88.24632195549063,0), FreeCAD.Vector(15.112562095290162,88.70821007196626,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.112562095290162,88.70821007196626,0), FreeCAD.Vector(14.686821619129375,89.10093759583631,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(14.686821619129375,89.10093759583631,0), FreeCAD.Vector(14.255812898145155,89.42355841209691,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(14.255812898145155,89.42355841209691,0), FreeCAD.Vector(13.820574270098255,89.67529529894344,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(13.820574270098255,89.67529529894344,0), FreeCAD.Vector(13.382154262966043,89.85554180016591,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(13.382154262966043,89.85554180016591,0), FreeCAD.Vector(12.941609068946764,89.96386368615518,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(12.941609068946764,89.96386368615518,0), FreeCAD.Vector(12.5,90.0,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(12.5,90.0,0), FreeCAD.Vector(0.0,90.0,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,90.0,0), FreeCAD.Vector(0.0,60.0,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,60.0,0), FreeCAD.Vector(0.9077519750572343,59.97771593979569,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(0.9077519750572343,59.97771593979569,0), FreeCAD.Vector(1.8133170960968705,59.91091744343564,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(1.8133170960968705,59.91091744343564,0), FreeCAD.Vector(2.714513777424191,59.799765434348444,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(2.714513777424191,59.799765434348444,0), FreeCAD.Vector(3.6091709572983746,59.644527687459764,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(3.6091709572983746,59.644527687459764,0), FreeCAD.Vector(4.4951333282103825,59.44557818409906,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(4.4951333282103825,59.44557818409906,0), FreeCAD.Vector(5.370266529207555,59.20339621104586,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(5.370266529207555,59.20339621104586,0), FreeCAD.Vector(6.232462287756071,58.91856520588588,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(6.232462287756071,58.91856520588588,0), FreeCAD.Vector(7.079643498754159,58.5917713514588,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(7.079643498754159,58.5917713514588,0), FreeCAD.Vector(7.90976922846022,58.2238019227837,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(7.90976922846022,58.2238019227837,0), FreeCAD.Vector(8.720839631280956,57.81554339044457,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(8.720839631280956,57.81554339044457,0), FreeCAD.Vector(9.510900767574604,57.367979285005035,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(9.510900767574604,57.367979285005035,0), FreeCAD.Vector(10.278049310862642,56.882187827597086,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(10.278049310862642,56.882187827597086,0), FreeCAD.Vector(11.020437133110015,56.35933933239193,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(11.020437133110015,56.35933933239193,0), FreeCAD.Vector(11.736275757027443,55.800693387210636,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(11.736275757027443,55.800693387210636,0), FreeCAD.Vector(12.42384066466984,55.20759581906674,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(12.42384066466984,55.20759581906674,0), FreeCAD.Vector(13.081475451951128,54.58147545195113,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(13.081475451951128,54.58147545195113,0), FreeCAD.Vector(13.70759581906674,53.92384066466984,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(13.70759581906674,53.92384066466984,0), FreeCAD.Vector(14.300693387210629,53.23627575702744,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(14.300693387210629,53.23627575702744,0), FreeCAD.Vector(14.859339332391933,52.520437133110015,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(14.859339332391933,52.520437133110015,0), FreeCAD.Vector(15.382187827597086,51.77804931086264,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.382187827597086,51.77804931086264,0), FreeCAD.Vector(15.867979285005035,51.0109007675746,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.867979285005035,51.0109007675746,0), FreeCAD.Vector(16.315543390444567,50.22083963128095,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(16.315543390444567,50.22083963128095,0), FreeCAD.Vector(16.7238019227837,49.40976922846022,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(16.7238019227837,49.40976922846022,0), FreeCAD.Vector(17.091771351458803,48.579643498754166,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.091771351458803,48.579643498754166,0), FreeCAD.Vector(17.418565205885884,47.73246228775607,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.418565205885884,47.73246228775607,0), FreeCAD.Vector(17.70339621104587,46.870266529207555,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.70339621104587,46.870266529207555,0), FreeCAD.Vector(17.945578184099062,45.995133328210386,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.945578184099062,45.995133328210386,0), FreeCAD.Vector(18.144527687459764,45.109170957298375,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.144527687459764,45.109170957298375,0), FreeCAD.Vector(18.299765434348444,44.214513777424195,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.299765434348444,44.214513777424195,0), FreeCAD.Vector(18.410917443435643,43.31331709609687,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.410917443435643,43.31331709609687,0), FreeCAD.Vector(18.477715939795686,42.40775197505724,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.477715939795686,42.40775197505724,0), FreeCAD.Vector(18.5,41.5,0)))
    qwm_doc.sketch_lflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.5,41.5,0), FreeCAD.Vector(21.5,41.5,0)))
    qwm_doc.addObject("Part::Extrusion", "lflare")
    qwm_doc.lflare.Base = qwm_doc.sketch_lflare
    qwm_doc.lflare.Dir = (0, 0, 0.1)
    qwm_doc.lflare.Solid = True
    lflare_viewObject = qwm_doc.lflare.ViewObject
    lflare_viewObject.Transparency = 60
    qwm_doc.lflare.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_uflare')
    qwm_doc.sketch_uflare.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,3.1496),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.5,41.5,0), FreeCAD.Vector(21.5,60.0,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.5,60.0,0), FreeCAD.Vector(21.489159105846554,61.47203022982254,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.489159105846554,61.47203022982254,0), FreeCAD.Vector(21.45666254004977,62.94051420988682,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.45666254004977,62.94051420988682,0), FreeCAD.Vector(21.402588589683027,64.40191423366085,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.402588589683027,64.40191423366085,0), FreeCAD.Vector(21.327067523629076,65.85270966048384,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.327067523629076,65.85270966048384,0), FreeCAD.Vector(21.230281278750894,67.28940539709791,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.230281278750894,67.28940539709791,0), FreeCAD.Vector(21.112463021589882,68.70854031763386,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(21.112463021589882,68.70854031763386,0), FreeCAD.Vector(20.973896586647186,70.1066956017666,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.973896586647186,70.1066956017666,0), FreeCAD.Vector(20.81491579260158,71.4805029709527,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.81491579260158,71.4805029709527,0), FreeCAD.Vector(20.63590363811099,72.82665280290846,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.63590363811099,72.82665280290846,0), FreeCAD.Vector(20.437291379135196,74.14190210477993,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.437291379135196,74.14190210477993,0), FreeCAD.Vector(20.219557490002448,75.42308232579666,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(20.219557490002448,75.42308232579666,0), FreeCAD.Vector(19.983226510722908,76.66710699058807,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(19.983226510722908,76.66710699058807,0), FreeCAD.Vector(19.728867783325803,77.870979134773,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(19.728867783325803,77.870979134773,0), FreeCAD.Vector(19.457094080264632,79.03179852490936,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(19.457094080264632,79.03179852490936,0), FreeCAD.Vector(19.16856012819463,80.14676864541056,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(19.16856012819463,80.14676864541056,0), FreeCAD.Vector(18.86396103067893,81.21320343559643,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.86396103067893,81.21320343559643,0), FreeCAD.Vector(18.544030593623166,82.22853376064877,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.544030593623166,82.22853376064877,0), FreeCAD.Vector(18.20953955747281,83.1903136008821,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.20953955747281,83.1903136008821,0), FreeCAD.Vector(17.8612937404319,84.09622594441934,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.8612937404319,84.09622594441934,0), FreeCAD.Vector(17.50013209717642,84.94408836907635,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.50013209717642,84.94408836907635,0), FreeCAD.Vector(17.126924697738996,85.73185830000816,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.126924697738996,85.73185830000816,0), FreeCAD.Vector(16.742570631433978,86.45763793045066,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(16.742570631433978,86.45763793045066,0), FreeCAD.Vector(16.34799584087254,87.1196787937033,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(16.34799584087254,87.1196787937033,0), FreeCAD.Vector(15.944150891285808,87.7163859753386,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.944150891285808,87.7163859753386,0), FreeCAD.Vector(15.53200868052998,88.24632195549063,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.53200868052998,88.24632195549063,0), FreeCAD.Vector(15.112562095290162,88.70821007196626,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.112562095290162,88.70821007196626,0), FreeCAD.Vector(14.686821619129375,89.10093759583631,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(14.686821619129375,89.10093759583631,0), FreeCAD.Vector(14.255812898145155,89.42355841209691,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(14.255812898145155,89.42355841209691,0), FreeCAD.Vector(13.820574270098255,89.67529529894344,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(13.820574270098255,89.67529529894344,0), FreeCAD.Vector(13.382154262966043,89.85554180016591,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(13.382154262966043,89.85554180016591,0), FreeCAD.Vector(12.941609068946764,89.96386368615518,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(12.941609068946764,89.96386368615518,0), FreeCAD.Vector(12.5,90.0,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(12.5,90.0,0), FreeCAD.Vector(0.0,90.0,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,90.0,0), FreeCAD.Vector(0.0,60.0,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,60.0,0), FreeCAD.Vector(0.9077519750572343,59.97771593979569,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(0.9077519750572343,59.97771593979569,0), FreeCAD.Vector(1.8133170960968705,59.91091744343564,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(1.8133170960968705,59.91091744343564,0), FreeCAD.Vector(2.714513777424191,59.799765434348444,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(2.714513777424191,59.799765434348444,0), FreeCAD.Vector(3.6091709572983746,59.644527687459764,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(3.6091709572983746,59.644527687459764,0), FreeCAD.Vector(4.4951333282103825,59.44557818409906,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(4.4951333282103825,59.44557818409906,0), FreeCAD.Vector(5.370266529207555,59.20339621104586,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(5.370266529207555,59.20339621104586,0), FreeCAD.Vector(6.232462287756071,58.91856520588588,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(6.232462287756071,58.91856520588588,0), FreeCAD.Vector(7.079643498754159,58.5917713514588,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(7.079643498754159,58.5917713514588,0), FreeCAD.Vector(7.90976922846022,58.2238019227837,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(7.90976922846022,58.2238019227837,0), FreeCAD.Vector(8.720839631280956,57.81554339044457,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(8.720839631280956,57.81554339044457,0), FreeCAD.Vector(9.510900767574604,57.367979285005035,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(9.510900767574604,57.367979285005035,0), FreeCAD.Vector(10.278049310862642,56.882187827597086,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(10.278049310862642,56.882187827597086,0), FreeCAD.Vector(11.020437133110015,56.35933933239193,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(11.020437133110015,56.35933933239193,0), FreeCAD.Vector(11.736275757027443,55.800693387210636,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(11.736275757027443,55.800693387210636,0), FreeCAD.Vector(12.42384066466984,55.20759581906674,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(12.42384066466984,55.20759581906674,0), FreeCAD.Vector(13.081475451951128,54.58147545195113,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(13.081475451951128,54.58147545195113,0), FreeCAD.Vector(13.70759581906674,53.92384066466984,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(13.70759581906674,53.92384066466984,0), FreeCAD.Vector(14.300693387210629,53.23627575702744,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(14.300693387210629,53.23627575702744,0), FreeCAD.Vector(14.859339332391933,52.520437133110015,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(14.859339332391933,52.520437133110015,0), FreeCAD.Vector(15.382187827597086,51.77804931086264,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.382187827597086,51.77804931086264,0), FreeCAD.Vector(15.867979285005035,51.0109007675746,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(15.867979285005035,51.0109007675746,0), FreeCAD.Vector(16.315543390444567,50.22083963128095,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(16.315543390444567,50.22083963128095,0), FreeCAD.Vector(16.7238019227837,49.40976922846022,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(16.7238019227837,49.40976922846022,0), FreeCAD.Vector(17.091771351458803,48.579643498754166,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.091771351458803,48.579643498754166,0), FreeCAD.Vector(17.418565205885884,47.73246228775607,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.418565205885884,47.73246228775607,0), FreeCAD.Vector(17.70339621104587,46.870266529207555,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.70339621104587,46.870266529207555,0), FreeCAD.Vector(17.945578184099062,45.995133328210386,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(17.945578184099062,45.995133328210386,0), FreeCAD.Vector(18.144527687459764,45.109170957298375,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.144527687459764,45.109170957298375,0), FreeCAD.Vector(18.299765434348444,44.214513777424195,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.299765434348444,44.214513777424195,0), FreeCAD.Vector(18.410917443435643,43.31331709609687,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.410917443435643,43.31331709609687,0), FreeCAD.Vector(18.477715939795686,42.40775197505724,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.477715939795686,42.40775197505724,0), FreeCAD.Vector(18.5,41.5,0)))
    qwm_doc.sketch_uflare.addGeometry(Part.LineSegment(FreeCAD.Vector(18.5,41.5,0), FreeCAD.Vector(21.5,41.5,0)))
    qwm_doc.addObject("Part::Extrusion", "uflare")
    qwm_doc.uflare.Base = qwm_doc.sketch_uflare
    qwm_doc.uflare.Dir = (0, 0, 0.1)
    qwm_doc.uflare.Solid = True
    uflare_viewObject = qwm_doc.uflare.ViewObject
    uflare_viewObject.Transparency = 60
    qwm_doc.uflare.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_iflare')
    qwm_doc.sketch_iflare.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,1.5748),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-18.5,41.5,0), FreeCAD.Vector(-18.5,60.0,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-18.5,60.0,0), FreeCAD.Vector(-18.510840894153446,61.47203022982254,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-18.510840894153446,61.47203022982254,0), FreeCAD.Vector(-18.54333745995023,62.94051420988682,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-18.54333745995023,62.94051420988682,0), FreeCAD.Vector(-18.597411410316973,64.40191423366085,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-18.597411410316973,64.40191423366085,0), FreeCAD.Vector(-18.672932476370924,65.85270966048384,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-18.672932476370924,65.85270966048384,0), FreeCAD.Vector(-18.769718721249106,67.28940539709791,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-18.769718721249106,67.28940539709791,0), FreeCAD.Vector(-18.887536978410118,68.70854031763386,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-18.887536978410118,68.70854031763386,0), FreeCAD.Vector(-19.026103413352814,70.1066956017666,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-19.026103413352814,70.1066956017666,0), FreeCAD.Vector(-19.18508420739842,71.4805029709527,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-19.18508420739842,71.4805029709527,0), FreeCAD.Vector(-19.36409636188901,72.82665280290846,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-19.36409636188901,72.82665280290846,0), FreeCAD.Vector(-19.562708620864804,74.14190210477993,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-19.562708620864804,74.14190210477993,0), FreeCAD.Vector(-19.780442509997552,75.42308232579666,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-19.780442509997552,75.42308232579666,0), FreeCAD.Vector(-20.016773489277092,76.66710699058807,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-20.016773489277092,76.66710699058807,0), FreeCAD.Vector(-20.271132216674197,77.870979134773,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-20.271132216674197,77.870979134773,0), FreeCAD.Vector(-20.542905919735368,79.03179852490936,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-20.542905919735368,79.03179852490936,0), FreeCAD.Vector(-20.83143987180537,80.14676864541056,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-20.83143987180537,80.14676864541056,0), FreeCAD.Vector(-21.13603896932107,81.21320343559643,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-21.13603896932107,81.21320343559643,0), FreeCAD.Vector(-21.455969406376834,82.22853376064877,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-21.455969406376834,82.22853376064877,0), FreeCAD.Vector(-21.79046044252719,83.1903136008821,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-21.79046044252719,83.1903136008821,0), FreeCAD.Vector(-22.1387062595681,84.09622594441934,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-22.1387062595681,84.09622594441934,0), FreeCAD.Vector(-22.49986790282358,84.94408836907635,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-22.49986790282358,84.94408836907635,0), FreeCAD.Vector(-22.873075302261004,85.73185830000816,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-22.873075302261004,85.73185830000816,0), FreeCAD.Vector(-23.257429368566022,86.45763793045066,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-23.257429368566022,86.45763793045066,0), FreeCAD.Vector(-23.65200415912746,87.1196787937033,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-23.65200415912746,87.1196787937033,0), FreeCAD.Vector(-24.05584910871419,87.7163859753386,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-24.05584910871419,87.7163859753386,0), FreeCAD.Vector(-24.46799131947002,88.24632195549063,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-24.46799131947002,88.24632195549063,0), FreeCAD.Vector(-24.887437904709838,88.70821007196626,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-24.887437904709838,88.70821007196626,0), FreeCAD.Vector(-25.313178380870625,89.10093759583631,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-25.313178380870625,89.10093759583631,0), FreeCAD.Vector(-25.744187101854845,89.42355841209691,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-25.744187101854845,89.42355841209691,0), FreeCAD.Vector(-26.179425729901745,89.67529529894344,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-26.179425729901745,89.67529529894344,0), FreeCAD.Vector(-26.617845737033957,89.85554180016591,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-26.617845737033957,89.85554180016591,0), FreeCAD.Vector(-27.058390931053236,89.96386368615518,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-27.058390931053236,89.96386368615518,0), FreeCAD.Vector(-27.5,90.0,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-27.5,90.0,0), FreeCAD.Vector(-40.0,90.0,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-40.0,90.0,0), FreeCAD.Vector(-40.0,60.0,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-40.0,60.0,0), FreeCAD.Vector(-39.09224802494276,59.97771593979569,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-39.09224802494276,59.97771593979569,0), FreeCAD.Vector(-38.18668290390313,59.91091744343564,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-38.18668290390313,59.91091744343564,0), FreeCAD.Vector(-37.285486222575805,59.799765434348444,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-37.285486222575805,59.799765434348444,0), FreeCAD.Vector(-36.390829042701625,59.644527687459764,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-36.390829042701625,59.644527687459764,0), FreeCAD.Vector(-35.504866671789614,59.44557818409906,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-35.504866671789614,59.44557818409906,0), FreeCAD.Vector(-34.629733470792445,59.20339621104586,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-34.629733470792445,59.20339621104586,0), FreeCAD.Vector(-33.76753771224393,58.91856520588588,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-33.76753771224393,58.91856520588588,0), FreeCAD.Vector(-32.92035650124584,58.5917713514588,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-32.92035650124584,58.5917713514588,0), FreeCAD.Vector(-32.09023077153978,58.2238019227837,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-32.09023077153978,58.2238019227837,0), FreeCAD.Vector(-31.279160368719044,57.81554339044457,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-31.279160368719044,57.81554339044457,0), FreeCAD.Vector(-30.489099232425396,57.367979285005035,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-30.489099232425396,57.367979285005035,0), FreeCAD.Vector(-29.72195068913736,56.882187827597086,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-29.72195068913736,56.882187827597086,0), FreeCAD.Vector(-28.979562866889985,56.35933933239193,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-28.979562866889985,56.35933933239193,0), FreeCAD.Vector(-28.263724242972557,55.800693387210636,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-28.263724242972557,55.800693387210636,0), FreeCAD.Vector(-27.57615933533016,55.20759581906674,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-27.57615933533016,55.20759581906674,0), FreeCAD.Vector(-26.91852454804887,54.58147545195113,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-26.91852454804887,54.58147545195113,0), FreeCAD.Vector(-26.292404180933257,53.92384066466984,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-26.292404180933257,53.92384066466984,0), FreeCAD.Vector(-25.699306612789368,53.23627575702744,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-25.699306612789368,53.23627575702744,0), FreeCAD.Vector(-25.140660667608067,52.520437133110015,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-25.140660667608067,52.520437133110015,0), FreeCAD.Vector(-24.617812172402914,51.77804931086264,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-24.617812172402914,51.77804931086264,0), FreeCAD.Vector(-24.132020714994965,51.0109007675746,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-24.132020714994965,51.0109007675746,0), FreeCAD.Vector(-23.684456609555433,50.22083963128095,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-23.684456609555433,50.22083963128095,0), FreeCAD.Vector(-23.2761980772163,49.40976922846022,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-23.2761980772163,49.40976922846022,0), FreeCAD.Vector(-22.908228648541197,48.579643498754166,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-22.908228648541197,48.579643498754166,0), FreeCAD.Vector(-22.581434794114116,47.73246228775607,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-22.581434794114116,47.73246228775607,0), FreeCAD.Vector(-22.296603788954133,46.870266529207555,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-22.296603788954133,46.870266529207555,0), FreeCAD.Vector(-22.054421815900938,45.995133328210386,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-22.054421815900938,45.995133328210386,0), FreeCAD.Vector(-21.855472312540236,45.109170957298375,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-21.855472312540236,45.109170957298375,0), FreeCAD.Vector(-21.700234565651552,44.214513777424195,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-21.700234565651552,44.214513777424195,0), FreeCAD.Vector(-21.589082556564357,43.31331709609687,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-21.589082556564357,43.31331709609687,0), FreeCAD.Vector(-21.52228406020431,42.40775197505724,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-21.52228406020431,42.40775197505724,0), FreeCAD.Vector(-21.5,41.5,0)))
    qwm_doc.sketch_iflare.addGeometry(Part.LineSegment(FreeCAD.Vector(-21.5,41.5,0), FreeCAD.Vector(-18.5,41.5,0)))
    qwm_doc.addObject("Part::Extrusion", "iflare")
    qwm_doc.iflare.Base = qwm_doc.sketch_iflare
    qwm_doc.iflare.Dir = (0, 0, 0.1)
    qwm_doc.iflare.Solid = True
    iflare_viewObject = qwm_doc.iflare.ViewObject
    iflare_viewObject.Transparency = 60
    qwm_doc.iflare.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject("Part::Mirroring", "iflare_mirror")
    qwm_doc.iflare_mirror.Source=qwm_doc.iflare
    qwm_doc.ActiveObject.Normal=(1,0,0)
    qwm_doc.ActiveObject.Base=(0,0,0)
    FreeCAD.Gui.ActiveDocument.iflare_mirror.ShapeColor=FreeCAD.Gui.ActiveDocument.iflare.ShapeColor
    FreeCAD.Gui.ActiveDocument.iflare_mirror.LineColor=FreeCAD.Gui.ActiveDocument.iflare.LineColor
    FreeCAD.Gui.ActiveDocument.iflare_mirror.PointColor=FreeCAD.Gui.ActiveDocument.iflare.PointColor
    FreeCAD.Gui.ActiveDocument.iflare.Visibility = False
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_ltrans')
    qwm_doc.sketch_ltrans.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,0.0,0), FreeCAD.Vector(40.0,0.0,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(40.0,0.0,0), FreeCAD.Vector(40.0,10.0,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(40.0,10.0,0), FreeCAD.Vector(39.09224802494277,10.03794312953707,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(39.09224802494277,10.03794312953707,0), FreeCAD.Vector(38.186682903903126,10.151681109825798,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(38.186682903903126,10.151681109825798,0), FreeCAD.Vector(37.285486222575805,10.340939936109397,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(37.285486222575805,10.340939936109397,0), FreeCAD.Vector(36.390829042701625,10.605263667298242,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(36.390829042701625,10.605263667298242,0), FreeCAD.Vector(35.50486667178962,10.944015524371864,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(35.50486667178962,10.944015524371864,0), FreeCAD.Vector(34.629733470792445,11.35637942443542,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(34.629733470792445,11.35637942443542,0), FreeCAD.Vector(33.76753771224393,11.841361946734846,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(33.76753771224393,11.841361946734846,0), FreeCAD.Vector(32.92035650124584,12.397794725894467,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(32.92035650124584,12.397794725894467,0), FreeCAD.Vector(32.09023077153978,13.024337266611536,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(32.09023077153978,13.024337266611536,0), FreeCAD.Vector(31.279160368719044,13.719480173026817,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(31.279160368719044,13.719480173026817,0), FreeCAD.Vector(30.489099232425396,14.481548784991432,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(30.489099232425396,14.481548784991432,0), FreeCAD.Vector(29.72195068913736,15.308707212469827,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(29.72195068913736,15.308707212469827,0), FreeCAD.Vector(28.979562866889985,16.198962758359684,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(28.979562866889985,16.198962758359684,0), FreeCAD.Vector(28.263724242972557,17.150170719073785,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(28.263724242972557,17.150170719073785,0), FreeCAD.Vector(27.57615933533016,18.16003955131879,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(27.57615933533016,18.16003955131879,0), FreeCAD.Vector(26.91852454804887,19.22613639262375,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(26.91852454804887,19.22613639262375,0), FreeCAD.Vector(26.292404180933257,20.34589292231892,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(26.292404180933257,20.34589292231892,0), FreeCAD.Vector(25.699306612789368,21.516611548845166,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(25.699306612789368,21.516611548845166,0), FreeCAD.Vector(25.140660667608067,22.73547190848835,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(25.140660667608067,22.73547190848835,0), FreeCAD.Vector(24.617812172402914,23.999537659882527,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(24.617812172402914,23.999537659882527,0), FreeCAD.Vector(24.132020714994965,25.30576355791352,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(24.132020714994965,25.30576355791352,0), FreeCAD.Vector(23.684456609555433,26.651002789981078,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(23.684456609555433,26.651002789981078,0), FreeCAD.Vector(23.2761980772163,28.03201455694611,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(23.2761980772163,28.03201455694611,0), FreeCAD.Vector(22.908228648541197,29.44547188049967,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(22.908228648541197,29.44547188049967,0), FreeCAD.Vector(22.581434794114116,30.887969618145068,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(22.581434794114116,30.887969618145068,0), FreeCAD.Vector(22.296603788954133,32.35603266648444,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(22.296603788954133,32.35603266648444,0), FreeCAD.Vector(22.054421815900938,33.846124333047186,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(22.054421815900938,33.846124333047186,0), FreeCAD.Vector(21.855472312540236,35.354654856491955,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.855472312540236,35.354654856491955,0), FreeCAD.Vector(21.700234565651552,36.8779900546561,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.700234565651552,36.8779900546561,0), FreeCAD.Vector(21.589082556564357,38.41246007961884,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.589082556564357,38.41246007961884,0), FreeCAD.Vector(21.52228406020431,39.95436825868633,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.52228406020431,39.95436825868633,0), FreeCAD.Vector(21.5,41.5,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.5,41.5,0), FreeCAD.Vector(18.5,41.5,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.5,41.5,0), FreeCAD.Vector(18.47771593979569,39.95436825868633,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.47771593979569,39.95436825868633,0), FreeCAD.Vector(18.410917443435643,38.41246007961884,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.410917443435643,38.41246007961884,0), FreeCAD.Vector(18.299765434348448,36.8779900546561,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.299765434348448,36.8779900546561,0), FreeCAD.Vector(18.144527687459764,35.35465485649196,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.144527687459764,35.35465485649196,0), FreeCAD.Vector(17.945578184099062,33.846124333047186,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(17.945578184099062,33.846124333047186,0), FreeCAD.Vector(17.703396211045863,32.35603266648444,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(17.703396211045863,32.35603266648444,0), FreeCAD.Vector(17.418565205885884,30.887969618145068,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(17.418565205885884,30.887969618145068,0), FreeCAD.Vector(17.091771351458803,29.445471880499674,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(17.091771351458803,29.445471880499674,0), FreeCAD.Vector(16.7238019227837,28.032014556946116,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(16.7238019227837,28.032014556946116,0), FreeCAD.Vector(16.315543390444567,26.651002789981074,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(16.315543390444567,26.651002789981074,0), FreeCAD.Vector(15.867979285005033,25.305763557913515,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(15.867979285005033,25.305763557913515,0), FreeCAD.Vector(15.382187827597086,23.99953765988253,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(15.382187827597086,23.99953765988253,0), FreeCAD.Vector(14.859339332391931,22.73547190848835,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(14.859339332391931,22.73547190848835,0), FreeCAD.Vector(14.300693387210634,21.516611548845166,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(14.300693387210634,21.516611548845166,0), FreeCAD.Vector(13.707595819066743,20.345892922318917,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(13.707595819066743,20.345892922318917,0), FreeCAD.Vector(13.08147545195113,19.22613639262375,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(13.08147545195113,19.22613639262375,0), FreeCAD.Vector(12.42384066466984,18.16003955131879,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(12.42384066466984,18.16003955131879,0), FreeCAD.Vector(11.73627575702744,17.150170719073788,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(11.73627575702744,17.150170719073788,0), FreeCAD.Vector(11.020437133110017,16.198962758359684,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(11.020437133110017,16.198962758359684,0), FreeCAD.Vector(10.278049310862642,15.308707212469827,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(10.278049310862642,15.308707212469827,0), FreeCAD.Vector(9.5109007675746,14.481548784991428,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(9.5109007675746,14.481548784991428,0), FreeCAD.Vector(8.720839631280956,13.719480173026817,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(8.720839631280956,13.719480173026817,0), FreeCAD.Vector(7.90976922846022,13.024337266611536,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(7.90976922846022,13.024337266611536,0), FreeCAD.Vector(7.079643498754162,12.397794725894467,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(7.079643498754162,12.397794725894467,0), FreeCAD.Vector(6.232462287756071,11.841361946734846,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(6.232462287756071,11.841361946734846,0), FreeCAD.Vector(5.370266529207553,11.356379424435417,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(5.370266529207553,11.356379424435417,0), FreeCAD.Vector(4.495133328210383,10.944015524371864,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(4.495133328210383,10.944015524371864,0), FreeCAD.Vector(3.609170957298374,10.605263667298242,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(3.609170957298374,10.605263667298242,0), FreeCAD.Vector(2.7145137774241923,10.340939936109397,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(2.7145137774241923,10.340939936109397,0), FreeCAD.Vector(1.81331709609687,10.151681109825798,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(1.81331709609687,10.151681109825798,0), FreeCAD.Vector(0.9077519750572354,10.03794312953707,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(0.9077519750572354,10.03794312953707,0), FreeCAD.Vector(1.1327982892113017e-15,10.0,0)))
    qwm_doc.sketch_ltrans.addGeometry(Part.LineSegment(FreeCAD.Vector(1.1327982892113017e-15,10.0,0), FreeCAD.Vector(0.0,0.0,0)))
    qwm_doc.addObject("Part::Extrusion", "ltrans")
    qwm_doc.ltrans.Base = qwm_doc.sketch_ltrans
    qwm_doc.ltrans.Dir = (0, 0, 0.1)
    qwm_doc.ltrans.Solid = True
    ltrans_viewObject = qwm_doc.ltrans.ViewObject
    ltrans_viewObject.Transparency = 60
    qwm_doc.ltrans.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_utrans')
    qwm_doc.sketch_utrans.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,3.1496),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,0.0,0), FreeCAD.Vector(40.0,0.0,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(40.0,0.0,0), FreeCAD.Vector(40.0,10.0,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(40.0,10.0,0), FreeCAD.Vector(39.09224802494277,10.03794312953707,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(39.09224802494277,10.03794312953707,0), FreeCAD.Vector(38.186682903903126,10.151681109825798,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(38.186682903903126,10.151681109825798,0), FreeCAD.Vector(37.285486222575805,10.340939936109397,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(37.285486222575805,10.340939936109397,0), FreeCAD.Vector(36.390829042701625,10.605263667298242,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(36.390829042701625,10.605263667298242,0), FreeCAD.Vector(35.50486667178962,10.944015524371864,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(35.50486667178962,10.944015524371864,0), FreeCAD.Vector(34.629733470792445,11.35637942443542,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(34.629733470792445,11.35637942443542,0), FreeCAD.Vector(33.76753771224393,11.841361946734846,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(33.76753771224393,11.841361946734846,0), FreeCAD.Vector(32.92035650124584,12.397794725894467,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(32.92035650124584,12.397794725894467,0), FreeCAD.Vector(32.09023077153978,13.024337266611536,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(32.09023077153978,13.024337266611536,0), FreeCAD.Vector(31.279160368719044,13.719480173026817,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(31.279160368719044,13.719480173026817,0), FreeCAD.Vector(30.489099232425396,14.481548784991432,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(30.489099232425396,14.481548784991432,0), FreeCAD.Vector(29.72195068913736,15.308707212469827,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(29.72195068913736,15.308707212469827,0), FreeCAD.Vector(28.979562866889985,16.198962758359684,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(28.979562866889985,16.198962758359684,0), FreeCAD.Vector(28.263724242972557,17.150170719073785,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(28.263724242972557,17.150170719073785,0), FreeCAD.Vector(27.57615933533016,18.16003955131879,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(27.57615933533016,18.16003955131879,0), FreeCAD.Vector(26.91852454804887,19.22613639262375,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(26.91852454804887,19.22613639262375,0), FreeCAD.Vector(26.292404180933257,20.34589292231892,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(26.292404180933257,20.34589292231892,0), FreeCAD.Vector(25.699306612789368,21.516611548845166,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(25.699306612789368,21.516611548845166,0), FreeCAD.Vector(25.140660667608067,22.73547190848835,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(25.140660667608067,22.73547190848835,0), FreeCAD.Vector(24.617812172402914,23.999537659882527,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(24.617812172402914,23.999537659882527,0), FreeCAD.Vector(24.132020714994965,25.30576355791352,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(24.132020714994965,25.30576355791352,0), FreeCAD.Vector(23.684456609555433,26.651002789981078,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(23.684456609555433,26.651002789981078,0), FreeCAD.Vector(23.2761980772163,28.03201455694611,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(23.2761980772163,28.03201455694611,0), FreeCAD.Vector(22.908228648541197,29.44547188049967,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(22.908228648541197,29.44547188049967,0), FreeCAD.Vector(22.581434794114116,30.887969618145068,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(22.581434794114116,30.887969618145068,0), FreeCAD.Vector(22.296603788954133,32.35603266648444,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(22.296603788954133,32.35603266648444,0), FreeCAD.Vector(22.054421815900938,33.846124333047186,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(22.054421815900938,33.846124333047186,0), FreeCAD.Vector(21.855472312540236,35.354654856491955,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.855472312540236,35.354654856491955,0), FreeCAD.Vector(21.700234565651552,36.8779900546561,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.700234565651552,36.8779900546561,0), FreeCAD.Vector(21.589082556564357,38.41246007961884,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.589082556564357,38.41246007961884,0), FreeCAD.Vector(21.52228406020431,39.95436825868633,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.52228406020431,39.95436825868633,0), FreeCAD.Vector(21.5,41.5,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(21.5,41.5,0), FreeCAD.Vector(18.5,41.5,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.5,41.5,0), FreeCAD.Vector(18.47771593979569,39.95436825868633,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.47771593979569,39.95436825868633,0), FreeCAD.Vector(18.410917443435643,38.41246007961884,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.410917443435643,38.41246007961884,0), FreeCAD.Vector(18.299765434348448,36.8779900546561,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.299765434348448,36.8779900546561,0), FreeCAD.Vector(18.144527687459764,35.35465485649196,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(18.144527687459764,35.35465485649196,0), FreeCAD.Vector(17.945578184099062,33.846124333047186,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(17.945578184099062,33.846124333047186,0), FreeCAD.Vector(17.703396211045863,32.35603266648444,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(17.703396211045863,32.35603266648444,0), FreeCAD.Vector(17.418565205885884,30.887969618145068,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(17.418565205885884,30.887969618145068,0), FreeCAD.Vector(17.091771351458803,29.445471880499674,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(17.091771351458803,29.445471880499674,0), FreeCAD.Vector(16.7238019227837,28.032014556946116,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(16.7238019227837,28.032014556946116,0), FreeCAD.Vector(16.315543390444567,26.651002789981074,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(16.315543390444567,26.651002789981074,0), FreeCAD.Vector(15.867979285005033,25.305763557913515,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(15.867979285005033,25.305763557913515,0), FreeCAD.Vector(15.382187827597086,23.99953765988253,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(15.382187827597086,23.99953765988253,0), FreeCAD.Vector(14.859339332391931,22.73547190848835,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(14.859339332391931,22.73547190848835,0), FreeCAD.Vector(14.300693387210634,21.516611548845166,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(14.300693387210634,21.516611548845166,0), FreeCAD.Vector(13.707595819066743,20.345892922318917,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(13.707595819066743,20.345892922318917,0), FreeCAD.Vector(13.08147545195113,19.22613639262375,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(13.08147545195113,19.22613639262375,0), FreeCAD.Vector(12.42384066466984,18.16003955131879,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(12.42384066466984,18.16003955131879,0), FreeCAD.Vector(11.73627575702744,17.150170719073788,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(11.73627575702744,17.150170719073788,0), FreeCAD.Vector(11.020437133110017,16.198962758359684,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(11.020437133110017,16.198962758359684,0), FreeCAD.Vector(10.278049310862642,15.308707212469827,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(10.278049310862642,15.308707212469827,0), FreeCAD.Vector(9.5109007675746,14.481548784991428,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(9.5109007675746,14.481548784991428,0), FreeCAD.Vector(8.720839631280956,13.719480173026817,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(8.720839631280956,13.719480173026817,0), FreeCAD.Vector(7.90976922846022,13.024337266611536,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(7.90976922846022,13.024337266611536,0), FreeCAD.Vector(7.079643498754162,12.397794725894467,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(7.079643498754162,12.397794725894467,0), FreeCAD.Vector(6.232462287756071,11.841361946734846,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(6.232462287756071,11.841361946734846,0), FreeCAD.Vector(5.370266529207553,11.356379424435417,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(5.370266529207553,11.356379424435417,0), FreeCAD.Vector(4.495133328210383,10.944015524371864,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(4.495133328210383,10.944015524371864,0), FreeCAD.Vector(3.609170957298374,10.605263667298242,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(3.609170957298374,10.605263667298242,0), FreeCAD.Vector(2.7145137774241923,10.340939936109397,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(2.7145137774241923,10.340939936109397,0), FreeCAD.Vector(1.81331709609687,10.151681109825798,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(1.81331709609687,10.151681109825798,0), FreeCAD.Vector(0.9077519750572354,10.03794312953707,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(0.9077519750572354,10.03794312953707,0), FreeCAD.Vector(1.1327982892113017e-15,10.0,0)))
    qwm_doc.sketch_utrans.addGeometry(Part.LineSegment(FreeCAD.Vector(1.1327982892113017e-15,10.0,0), FreeCAD.Vector(0.0,0.0,0)))
    qwm_doc.addObject("Part::Extrusion", "utrans")
    qwm_doc.utrans.Base = qwm_doc.sketch_utrans
    qwm_doc.utrans.Dir = (0, 0, 0.1)
    qwm_doc.utrans.Solid = True
    utrans_viewObject = qwm_doc.utrans.ViewObject
    utrans_viewObject.Transparency = 60
    qwm_doc.utrans.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_strip')
    qwm_doc.sketch_strip.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,1.5748),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_strip.addGeometry(Part.LineSegment(FreeCAD.Vector(18.5,0.0,0), FreeCAD.Vector(21.5,0.0,0)))
    qwm_doc.sketch_strip.addGeometry(Part.LineSegment(FreeCAD.Vector(21.5,0.0,0), FreeCAD.Vector(21.5,41.5,0)))
    qwm_doc.sketch_strip.addGeometry(Part.LineSegment(FreeCAD.Vector(21.5,41.5,0), FreeCAD.Vector(18.5,41.5,0)))
    qwm_doc.sketch_strip.addGeometry(Part.LineSegment(FreeCAD.Vector(18.5,41.5,0), FreeCAD.Vector(18.5,0.0,0)))
    qwm_doc.addObject("Part::Extrusion", "strip")
    qwm_doc.strip.Base = qwm_doc.sketch_strip
    qwm_doc.strip.Dir = (0, 0, 0.1)
    qwm_doc.strip.Solid = True
    strip_viewObject = qwm_doc.strip.ViewObject
    strip_viewObject.Transparency = 60
    qwm_doc.strip.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject("Part::MultiFuse","Fusion1")
    qwm_doc.Fusion1.Shapes = [qwm_doc.lflare,qwm_doc.ltrans,]
    qwm_doc.Fusion1.Medium = qwm_doc.lflare.Medium
    FreeCAD.Gui.activeDocument().lflare.Visibility = False
    FreeCAD.Gui.activeDocument().ltrans.Visibility = False
    qwm_doc.Fusion1.Label = 'lflare'
    qwm_doc.addObject("Part::MultiFuse","Fusion2")
    qwm_doc.Fusion2.Shapes = [qwm_doc.uflare,qwm_doc.utrans,]
    qwm_doc.Fusion2.Medium = qwm_doc.uflare.Medium
    FreeCAD.Gui.activeDocument().uflare.Visibility = False
    FreeCAD.Gui.activeDocument().utrans.Visibility = False
    qwm_doc.Fusion2.Label = 'uflare'
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_m1')
    qwm_doc.sketch_m1.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_m1.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,-0.1,0), FreeCAD.Vector(14.0,-0.1,0)))
    qwm_doc.sketch_m1.addGeometry(Part.LineSegment(FreeCAD.Vector(14.0,-0.1,0), FreeCAD.Vector(14.0,0.0,0)))
    qwm_doc.sketch_m1.addGeometry(Part.LineSegment(FreeCAD.Vector(14.0,0.0,0), FreeCAD.Vector(0.0,0.0,0)))
    qwm_doc.sketch_m1.addGeometry(Part.LineSegment(FreeCAD.Vector(0.0,0.0,0), FreeCAD.Vector(0.0,-0.1,0)))
    qwm_doc.addObject("Part::Extrusion", "m1")
    qwm_doc.m1.Base = qwm_doc.sketch_m1
    qwm_doc.m1.Dir = (0, 0, 3.1496)
    qwm_doc.m1.Solid = True
    m1_viewObject = qwm_doc.m1.ViewObject
    m1_viewObject.Transparency = 60
    qwm_doc.m1.Medium = QW_Modeller.getQWMedium("metal")
    qwm_doc.addObject('Sketcher::SketchObject', 'sketch_m2')
    qwm_doc.sketch_m2.Placement = FreeCAD.Placement(FreeCAD.Vector(0.0,0.0,0.0),FreeCAD.Rotation(0.0, 0.0, 0.0, 1.0))
    qwm_doc.sketch_m2.addGeometry(Part.LineSegment(FreeCAD.Vector(26.0,-0.1,0), FreeCAD.Vector(40.0,-0.1,0)))
    qwm_doc.sketch_m2.addGeometry(Part.LineSegment(FreeCAD.Vector(40.0,-0.1,0), FreeCAD.Vector(40.0,0.0,0)))
    qwm_doc.sketch_m2.addGeometry(Part.LineSegment(FreeCAD.Vector(40.0,0.0,0), FreeCAD.Vector(26.0,0.0,0)))
    qwm_doc.sketch_m2.addGeometry(Part.LineSegment(FreeCAD.Vector(26.0,0.0,0), FreeCAD.Vector(26.0,-0.1,0)))
    qwm_doc.addObject("Part::Extrusion", "m2")
    qwm_doc.m2.Base = qwm_doc.sketch_m2
    qwm_doc.m2.Dir = (0, 0, 3.1496)
    qwm_doc.m2.Solid = True
    m2_viewObject = qwm_doc.m2.ViewObject
    m2_viewObject.Transparency = 60
    qwm_doc.m2.Medium = QW_Modeller.getQWMedium("metal")
